### ISSUE TITLE
FULLTEXT with sort on same field not working

### ISSUE THREAD

**Issue by ChristyG** [arangodb/arangodb#10078]
I was trying to do a search using FULLTEXT and sort on the same field,
For the following query
for u in  FULLTEXT(User, 'firstName','prefix:a')  sort u.name asc return u

sort is not applied in query. Execution plan is as follows

Execution plan:
 Id   NodeType        Est.   Comment
  1   SingletonNode      1   * ROOT
  7   IndexNode         54     - FOR u IN User   /* fulltext index scan */
  6   ReturnNode        54       - RETURN u

But for sorting with descending work as expected. 
for u in  FULLTEXT(User, 'firstName','prefix:a')  sort u.name desc return u

Execution plan:
 Id   NodeType          Est.   Comment
  1   SingletonNode        1   * ROOT
  7   IndexNode           54     - FOR u IN User   /* fulltext index scan */
  4   CalculationNode     54       - LET #3 = u.`firstName`   /* attribute expression */   /* collections used: u : User */
  5   SortNode            54       - SORT #3 DESC
  6   ReturnNode          54       - RETURN u

## My Environment

__ArangoDB Version__:        
 __Storage Engine__:             
* __Deployment Mode__:       
* __Deployment Strategy__:   
* __Configuration__:               
* __Infrastructure__:               
 __Operating System__:        
* __Total RAM in your machine__:        
* __Disks in use__:        
* __Used Package__:              

## Component, Query & Data

__Affected feature__:

__AQL query (if applicable)__:

__AQL explain (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. 
2. 
3. 

__Problem__:

__Expected result__:

**Comment by jsteemann** [comment]
@ChristyG : because the ArangoDB version information is missing in this ticket, I tried this in 3 branches: 3.3, 3.4 and 3.5, with the RocksDB and the MMFiles storage engine.
I couldn't reproduce the issue in any of these combinations.
Here is my test setup:
```js
db._create("User");
db.User.ensureIndex({ fields: ["firstName"], type: "fulltext" });
db._explain(`for u in FULLTEXT(User, 'firstName','prefix:a') sort u.name asc return u`);
```

It produces something like this:
```
Query String (72 chars, cacheable: false):
 for u in FULLTEXT(User, 'firstName','prefix:a') sort u.name asc return u

Execution plan:
 Id   NodeType          Est.   Comment
  1   SingletonNode        1   * ROOT
  7   IndexNode            0     - FOR u IN User   /* fulltext index scan */
  4   CalculationNode      0       - LET #3 = u.`name`   /* attribute expression */   /* collections used: u : User */
  5   SortNode             0       - SORT #3 ASC
  6   ReturnNode           0       - RETURN u

Indexes used:
 By   Type       Collection   Unique   Sparse   Selectivity   Fields            Ranges
  7   fulltext   User         false    true             n/a   [ `firstName` ]   FULLTEXT("User", "firstName", "prefix:a")

Optimization rules applied:
 Id   RuleName
  1   replace-function-with-index
  2   inline-subqueries
```
Exact query execution plan output will vary depending on ArangoDB version, but in all combinations I got a SortNode as expected.

As I cannot reproduce the issue locally, please provide more information about the version of ArangoDB you are using and some setup data for reproduction.

**Comment by graetzer** [comment]
technically the fulltext index with the rocksdb storage engine is sorted lexographically ascending ?

**Comment by jsteemann** [comment]
@graetzer : but IIRC there isn't any optimizer rule that would remove a SORT instruction in case a FULLTEXT query is used.

**Comment by ChristyG** [comment]
Version is 3.4.5   RocksDB
FULLTEXT field and sort field needs to be same.
Here sort was on name and FULLTEXT was on firstName. In this case it will work,
db._explain(`for u in FULLTEXT(User, 'firstName','prefix:a') sort u.name asc return u`);

If both FULLTEXT prefix and sort is on same field issue occurs

**Comment by jsteemann** [comment]
True, you just put me on the wrong track with your original post:

> For the following query
> for u in FULLTEXT(User, 'firstName','prefix:a') sort u.name asc return u
> sort is not applied in query.

But when I change the query so that the fulltext attribute and the sort attribute are identical, I can see that the SORT instruction is indeed removed. However the results are not sorted.

**Comment by ChristyG** [comment]
Oh, sorry for the wrong query earlier. 
Is there any workaround available with FULLTEXT and ascending sort?

**Comment by jsteemann** [comment]
As a workaround, you can change the query from
```
for u in FULLTEXT(User, 'name','prefix:A') sort u.name asc return u
```
to 
```
for u in FULLTEXT(User, 'name','prefix:A') sort NOOPT(u.name) asc return u
```

**Comment by jsteemann** [comment]
Fixed via the above PRs, targeting ArangoDB versions 3.4.9 and 3.5.2.

**Comment by maxkernbach** [comment]
Hi @ChristyG,

Version 3.4.9, which includes a fix for FULLTEXT with sort on same field, has just been released.
In case this issue still occurs after upgrading, please comment and we will reopen the ticket.

Please find the latest release in the [download section](https://www.arangodb.com/download/).
