### ISSUE TITLE
Lack of optimization using nested AQL functions

### ISSUE THREAD

**Issue by faustinoribeiro** [arangodb/arangodb#10797]
## My Environment

* __ArangoDB Version__:  3.4.7
* __Storage Engine__:  RocksDB
* __Deployment Mode__:   Single Server
* __Deployment Strategy__:   Manual Start in Docker
* __Configuration__:
* __Infrastructure__: own
* __Operating System__: Mint 19.3
* __Total RAM in your machine__:  32Gb
* __Disks in use__:  SSD
* __Used Package__:  Docker - official Docker library

## Component, Query & Data

__Affected feature__: AQL query 

__Size of your Dataset on disk__: 30Gb

__Replication Factor & Number of Shards (Cluster only)__: no replication

## Steps to reproduce

1. create a 'Member' collection
2. create a ```unique``` and ```sparse``` hash index on 'normalizedAccountEmail'
3. populate the collection with thousands of documents:
```
{ 
    "normalizedAccountEmail": "email that has been trimmed and upper-cased" 
}
```
and
```
{ 
    "normalizedAccountEmail": null
}
```

4. execute query:
```
LET normalizedEmail = UPPER(TRIM(@__accountEmail))

FOR member
IN Member
FILTER member.normalizedAccountEmail == normalizedEmail
RETURN member
```
__Problem__:
The query is very slow. It seems that using ```UPPER(TRIM(@__accountEmail))``` prevents the hash index on ```normalizedAccountEmail``` field to be used. If UPPER or TRIM is removed (for example: ```LET normalizedAccountEmail = UPPER(@__accountEmail)```), then the index is used properly. It seems the optimizer fails to identify ```normalizedEmail``` variable as being "constant".

I fixed the query by adding an additional condition in the filter clause: 
```
LET normalizedEmail = UPPER(TRIM(@__accountEmail))

FOR member
IN Member
FILTER member.normalizedAccountEmail != null 
   && member.normalizedAccountEmail == normalizedEmail
RETURN member
```
I don't understand why though. Not sure this is a bug/incorrect optimization or if I am just missing something.

__Expected result__:
Using the result of nested AQL functions should not result in very counter-intuitive query performance.

**Comment by markuspf** [comment]
Hi!

As the explanation of the query shows, you're right that the nested functions are not optimized away on 3.4.7.

```
Execution plan:            
 Id   NodeType                  Est.   Comment
  1   SingletonNode                1   * ROOT                                                                                                               
  2   CalculationNode              1     - LET normalizedEmail = UPPER("foo")   /* simple expression */                 
  3   EnumerateCollectionNode      0     - FOR member IN Member   /* full collection scan */
  4   CalculationNode              0       - LET #2 = ((member.`normalizedAccountEmail` != null) && (member.`normalizedAccountEmail` == normalizedEmail))   
/* simple expression */   /* collections used: member : Member */                                                                                           
  5   FilterNode                   0       - FILTER #2        
  6   ReturnNode                   0       - RETURN member
                                                                                                                                                            Indexes used:                                                                                                                                               
 none                                                                         
                                                                                                                                                            
Functions used:                                                                                                                                             
 Name    Deterministic   Cacheable   Uses V8
 UPPER   true            true        false  
                                       
Optimization rules applied:                                                   
 none                 
```

alas on 3.5 this problem is solved:

```
xecution plan:                                                               
 Id   NodeType                  Est.   Comment                                                                                                              
  1   SingletonNode                1   * ROOT                                                                                                                 3   EnumerateCollectionNode      0     - FOR member IN Member   /* full collection scan */
  4   CalculationNode              0       - LET #2 = ((member.`normalizedAccountEmail` != null) && (member.`normalizedAccountEmail` == "FOO"))   /* simple 
expression */   /* collections used: member : Member */                       
  5   FilterNode                   0       - FILTER #2                                                                                                      
  6   ReturnNode                   0       - RETURN member                                                                                                  
                                                                              
Indexes used:
 none                                                                         
                                                                              
Optimization rules applied:                                                   
 Id   RuleName                                                                
  1   remove-unnecessary-calculations         
```

Is upgrading an option for you?

**Comment by jsteemann** [comment]
@markuspf : in 3.5 this problem is not solved. Looking at the execution plan output, it seems that it is incomplete. It shows neither an EnumerateCollectionNode nor an IndexNode. Please can you check it with the exact query again, and with a sparse index?

@faustinoribeiro : I was able to reproduce the problem.
It is caused by nested function calls not being optimized at query compile time.
Because of this, the optimizer does not know what the exact value of `normalizedEmail` will be when executing the filter `FILTER member.normalizedAccountEmail == normalizedEmail`.
And as it cannot exclude the possibility that the compare value is `null`, it will not use the sparse index. Note that sparse indexes do not include documents in which the indexed attribute is either `null` or not present. Using a sparse index is only taken into consideration by the optimizer if it can prove the lookup value will not be `null`.
Thus the workaround for current 3.4/3.5/3.6 is to make the index non-sparse. 

Obviously the query optimizer can be made a bit more intelligent here and just optimize nested function calls as well. I will work on a fix for this.

**Comment by faustinoribeiro** [comment]
Thank you for the quick response. I suspected that the collection values possibly being null played a role. I will also mention that in my case I have a ```FILTER @__accountEmail != null``` statement at the start of the query (not shown in my initial comment), so there is a guarantee that ```UPPER(TRIM(@__accounEmail))``` is not executed against a null value.
I will update to version 3.5 or 3.6 since it is still an option at this time. Thanks for the great work.

**Comment by markuspf** [comment]
@jsteemann Two issues with my comment: 
  1. Copy & Paste formatting was off, so the query plan was not showing correctly
  2. I hadn't created an index in my test example and only focused on the optimisation behaviour (which does change from 3.4.7 to 3.5).

On 3.4.7 with unique and sparse index:

```

Query String:
 LET normalizedEmail = UPPER(TRIM(@__accountEmail))  FOR member IN Member FILTER 
 member.normalizedAccountEmail != null     && member.normalizedAccountEmail == normalizedEmail RETURN 
 member

Execution plan:
 Id   NodeType          Est.   Comment
  1   SingletonNode        1   * ROOT
  7   IndexNode            1     - FOR member IN Member   /* hash index scan */
  8   CalculationNode      1       - LET #2 = (member.`normalizedAccountEmail` != null)   /* simple expression */   /* collections used: member : Member */
  5   FilterNode           1       - FILTER #2
  6   ReturnNode           1       - RETURN member

Indexes used:
 By   Type   Collection   Unique   Sparse   Selectivity   Fields                         Ranges
  7   hash   Member       false    false       100.00 %   [ `normalizedAccountEmail` ]   (member.`normalizedAccountEmail` == UPPER("foo"))

Optimization rules applied:
 Id   RuleName
  1   use-indexes
  2   remove-filter-covered-by-index
  3   remove-unnecessary-calculations-2
```

On 3.5 with unique and sparse index:

```
Query String (187 chars, cacheable: true):
 LET normalizedEmail = UPPER(TRIM(@__accountEmail))  FOR member IN Member FILTER 
 member.normalizedAccountEmail != null     && member.normalizedAccountEmail == normalizedEmail RETURN 
 member

Execution plan:
 Id   NodeType        Est.   Comment
  1   SingletonNode      1   * ROOT
  7   IndexNode          0     - FOR member IN Member   /* hash index scan */
  6   ReturnNode         0       - RETURN member

Indexes used:
 By   Name                      Type   Collection   Unique   Sparse   Selectivity   Fields                         Ranges
  7   idx_1655237229672398848   hash   Member       true     true        100.00 %   [ `normalizedAccountEmail` ]   (member.`normalizedAccountEmail` == "FOO")

Optimization rules applied:
 Id   RuleName
  1   remove-unnecessary-calculations
  2   use-indexes
  3   remove-filter-covered-by-index
  4   remove-unnecessary-calculations-2

```

If making the index non-sparse in 3.4.7:

```
Query String:
 LET normalizedEmail = UPPER(TRIM(@__accountEmail))  FOR member IN Member FILTER 
 member.normalizedAccountEmail != null     && member.normalizedAccountEmail == normalizedEmail RETURN 
 member

Execution plan:
 Id   NodeType          Est.   Comment
  1   SingletonNode        1   * ROOT
  7   IndexNode            1     - FOR member IN Member   /* hash index scan */
  8   CalculationNode      1       - LET #2 = (member.`normalizedAccountEmail` != null)   /* simple expression */   /* collections used: member : Member */
  5   FilterNode           1       - FILTER #2
  6   ReturnNode           1       - RETURN member

Indexes used:
 By   Type   Collection   Unique   Sparse   Selectivity   Fields                         Ranges
  7   hash   Member       true     false       100.00 %   [ `normalizedAccountEmail` ]   (member.`normalizedAccountEmail` == UPPER("foo"))

Optimization rules applied:
 Id   RuleName
  1   use-indexes
  2   remove-filter-covered-by-index
  3   remove-unnecessary-calculations-2
```

**Comment by faustinoribeiro** [comment]
@markuspf In your tests above you run the query with ```member.normalizedAccountEmail != null``` in the filter. That's the "trick" I used to solve the initial issue (it somehow forces the use of the index). You should rerun the query plans tests without that condition in the filter.

**Comment by markuspf** [comment]
Just for completeness if anyone comes across this issue in the future, I'll add this here;

3.4.7 unique and sparse index
```
Query String:
 LET normalizedEmail = UPPER(TRIM(@__accountEmail))  FOR member IN Member FILTER 
 member.normalizedAccountEmail == normalizedEmail RETURN member

Execution plan:
 Id   NodeType                  Est.   Comment
  1   SingletonNode                1   * ROOT
  2   CalculationNode              1     - LET normalizedEmail = UPPER("foo")   /* simple expression */
  3   EnumerateCollectionNode      0     - FOR member IN Member   /* full collection scan */
  4   CalculationNode              0       - LET #2 = (member.`normalizedAccountEmail` == normalizedEmail)   /* simple expression */   /* collections used: member : Member */
  5   FilterNode                   0       - FILTER #2
  6   ReturnNode                   0       - RETURN member

Indexes used:
 none

Functions used:
 Name    Deterministic   Cacheable   Uses V8
 UPPER   true            true        false  

Optimization rules applied:
 none
```

3.4.7 unique and non-sparse index
```
Query String:
 LET normalizedEmail = UPPER(TRIM(@__accountEmail))  FOR member IN Member FILTER 
 member.normalizedAccountEmail == normalizedEmail RETURN member

Execution plan:
 Id   NodeType          Est.   Comment
  1   SingletonNode        1   * ROOT
  2   CalculationNode      1     - LET normalizedEmail = UPPER("foo")   /* simple expression */
  7   IndexNode            0     - FOR member IN Member   /* hash index scan */
  6   ReturnNode           0       - RETURN member

Indexes used:
 By   Type   Collection   Unique   Sparse   Selectivity   Fields                         Ranges
  7   hash   Member       true     false       100.00 %   [ `normalizedAccountEmail` ]   (member.`normalizedAccountEmail` == UPPER("foo"))

Functions used:
 Name    Deterministic   Cacheable   Uses V8
 UPPER   true            true        false  

Optimization rules applied:
 Id   RuleName
  1   use-indexes
  2   remove-filter-covered-by-index
  3   remove-unnecessary-calculations-2
```

3.5 unique and sparse index

```
Query String (142 chars, cacheable: true):
 LET normalizedEmail = UPPER(TRIM(@__accountEmail))  FOR member IN Member FILTER 
 member.normalizedAccountEmail == normalizedEmail RETURN member

Execution plan:
 Id   NodeType        Est.   Comment
  1   SingletonNode      1   * ROOT
  7   IndexNode          0     - FOR member IN Member   /* hash index scan */
  6   ReturnNode         0       - RETURN member

Indexes used:
 By   Name                      Type   Collection   Unique   Sparse   Selectivity   Fields                         Ranges
  7   idx_1655267095490854912   hash   Member       true     true        100.00 %   [ `normalizedAccountEmail` ]   (member.`normalizedAccountEmail` == "FOO")

Optimization rules applied:
 Id   RuleName
  1   remove-unnecessary-calculations
  2   use-indexes
  3   remove-filter-covered-by-index
  4   remove-unnecessary-calculations-2
```

**Comment by maxkernbach** [comment]
Hi all,

I am closing this issue since the optimization is fixed in versions 3.5, 3.6 and a workaround for the query is available in 3.4 (make the index non-sparse).
