### ISSUE TITLE
Queries with a sort against a view hang when returning an array element from a variable

### ISSUE THREAD

**Issue by dremekie** [arangodb/arangodb#10911]
## My Environment

* __ArangoDB Version__:        3.60
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Configuration__:               N/A
* __Infrastructure__:               Own
* __Operating System__:        MacOS 10.14.5
* __Total RAM in your machine__:        16GB
* __Disks in use__:        SSD
* __Used Package__:           

## Component, Query & Data

__Affected feature__: Arango Search View

The following hangs and cannot be killed and continues to consume a lot of CPU (the collection has only two records).

```
FOR x IN `test-view`
LIMIT 5
SORT x.`_id`

LET y = ( 
    RETURN { 
      values: x
    } 
) 

RETURN y[0]
```

It works when I return `y` instead of `y[0]`

```
FOR x IN `test-view`
LIMIT 5
SORT x.`_id`

LET y = ( 
    RETURN { 
      values: x
    } 
) 

RETURN y
```

I can return `y[0]` without a `SORT`.

```
FOR x IN `test-view`
LIMIT 5

LET y = ( 
    RETURN { 
      values: x
    } 
) 

RETURN y[0]
```

I can return `y[0]` with a `SORT` if I bypass the view and go straight to the underlying collection.

```
FOR x IN `test`
LIMIT 5
SORT x.`_id`

LET y = ( 
    RETURN { 
      values: x
    } 
) 

RETURN y[0]
```

I crteated the collection and view as follows:

```
db.test.drop()
db._create("test")
db.test.save({ "id": "1", "visits": [{ "city": "Toronto", "country": "Canada" }, { "city": "Vancouver", "country": "Canada" }, { "city": "Paris", "country": "France" }, { "city": "Paris", "country": "Canada" }] })
db.test.save({ "id": "2", "visits": [{ "city": "Paris", "country": "France" }, { "city": "Toronto", "country": "Canada" }] })
db._createView("test-view", "arangosearch", {links: {test: {includeAllFields: true}}})
```

**Comment by OmarAyo** [comment]
Hi @dremekie,

Thanks for reporting this I will do a quick test a see what I get 

Best,

**Comment by OmarAyo** [comment]
Hi @dremekie 

I was able to reproduce and this is a known issue now as reported in this ticket as well https://github.com/arangodb/arangodb/issues/10845 

This has been already fixed in devel and fix will be part of 3.6.1.

For the time being you can pass the following option to the arangod starup commad to be up and running

```
--query.optimizer-rules "-late-document-materialization"
--query.optimizer-rules "-late-document-materialization-arangosearch" 
```
Best,

**Comment by maxkernbach** [comment]
Hi @dremekie,

Version 3.6.1, which includes a fix for the reported bug has just been released.
In case the issue persists, please comment and we will reopen this ticket.

You can find the latest release in the [download section](https://www.arangodb.com/download/).
