### ISSUE TITLE
ANALYZER function doesn't correctly process != OR queries

### ISSUE THREAD

**Issue by jebbench** [arangodb/arangodb#11104]
## My Environment

* __ArangoDB Version__:        3.6.1
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start in Docker
* __Configuration__:               Out the box docker image with authentication disabled
* __Infrastructure__:               GKE/Docker for Windows
* __Operating System__:        N/A
* __Total RAM in your machine__:        16gb
* __Disks in use__:        SSD
* __Used Package__:              Docker - official Docker library

## Component, Query & Data

__Affected feature__:
ArangoSearch AQL query

__AQL query (if applicable)__:
```
FOR s IN `v-site`
    SEARCH ANALYZER(s.attributes.country.value != "w" OR false, "identity")
    RETURN s.attributes.country.value
```

__AQL explain (if applicable)__:
```
Query String (131 chars, cacheable: true):
 FOR s IN `v-site`
     SEARCH ANALYZER(s.attributes.country.value != "w" OR false, "identity")
     RETURN s.attributes.country.value

Execution plan:
 Id   NodeType            Est.   Comment
  1   SingletonNode          1   * ROOT
  2   EnumerateViewNode      1     - FOR s IN v-site SEARCH ANALYZER(((s.`attributes`.`country`.`value` != "w") || false), "identity")   /* view query */
  3   CalculationNode        1       - LET #1 = s.`attributes`.`country`.`value`   /* attribute expression */
  4   ReturnNode             1       - RETURN #1

Indexes used:

Optimization rules applied:
 Id   RuleName
  1   handle-arangosearch-views
```

__Dataset__:
```
[
  {
    "attributes": {
      "country": {
        "type": "string",
        "value": "E"
      }
    }
  },
  {
    "attributes": {
      "country": {
        "type": "string",
        "value": "E"
      }
    }
  },
  {
    "attributes": {
      "country": {
        "type": "string",
        "value": "E"
      }
    }
  },
  {
    "attributes": {
      "country": {
        "type": "string",
        "value": "W"
      }
    }
  },
  {
    "attributes": {
      "country": {
        "type": "string",
        "value": "E"
      }
    }
  },
  {
    "attributes": {
      "country": {
        "type": "string",
        "value": "E"
      }
    }
  },
  {
    "attributes": {
      "country": {
        "type": "string",
        "value": "E"
      }
    }
  },
  {
    "attributes": {
      "country": {
        "type": "string",
        "value": "E"
      }
    }
  },
  {
    "attributes": {
      "country": {
        "type": "string",
        "value": "W"
      }
    }
  },
  {
    "attributes": {
      "country": {
        "type": "string",
        "value": "E"
      }
    }
  }
]
```

__Size of your Dataset on disk__:
N/A

__Replication Factor & Number of Shards (Cluster only)__:
N/A

## Steps to reproduce

1. Create a site collection containing the data above.
2. Create the view 'v-site' (defaults are fine)
3. Run the query above

__Problem__:
There are no results.

If you remove the "OR false" from the query then it works as expected.

__Expected result__:
There should be results from this query.

**Comment by jebbench** [comment]
This only affects `!=` queries.

This query works as expected:
```
FOR s IN `v-site`
    SEARCH ANALYZER(s.attributes.country.value == "E" OR false, "identity")
    RETURN s.attributes.country.value
```

**Comment by Simran-B** [comment]
Shouldn't the operation be more like `SEARCH ANALYZER(s.attributes.country.value != "w" OR s.attributes.country.value == false, "identity")`?

The second condition on its own is just `false` in your example, which I expect to return no results ever.

**Comment by jebbench** [comment]
Hi Simran,

I've substituted in my actual expression for false to make a simpler reproduction.

Does the below read clearer as to my intent?
```
FOR s IN `v-site`
    SEARCH ANALYZER(s.attributes.country.value != "w" OR "another expression" == "that isn't true", "identity")
    RETURN s.attributes.country.value
```

**Comment by Simran-B** [comment]
@jebbench  I inserted your dataset into a collection `site` and created a View `v-site` with following links:

```json
  "links": {
    "site": {
      "analyzers": [
        "identity"
      ],
      "includeAllFields": true,
    }
  }
```

If I then run the following query:

```js
FOR s IN `v-site`
    SEARCH ANALYZER(s.attributes.country.value != "w" or s.attributes.country.type != "foobar", "identity")
    RETURN s.attributes.country.value
```

… I get 10 results:

```json
[
  "E",
  "E",
  "E",
  "W",
  "E",
  "E",
  "E",
  "E",
  "W",
  "E"
]
```

Please share your View definition and the actual second expression that you use, otherwise it will not be possible to reproduce the exact circumstances.

**Comment by jebbench** [comment]
Hi Simran,

Running the below in arangosh demonstrates the issue:

**Setup:**
```
db._createDatabase('test-11104')
db._useDatabase('test-11104')
db._create('collection')
db._createView('v-collection', 'arangosearch', {
	links: {collection: {fields: {attributes: {includeAllFields: true, storeValues: 'id'}}}}
})


let col = db.collection
let data = [
  {
    "attributes": {
      "country": {
        "type": "string",
        "value": "E"
      }
    }
  },
  {
    "attributes": {
      "country": {
        "type": "string",
        "value": "E"
      }
    }
  },
  {
    "attributes": {
      "country": {
        "type": "string",
        "value": "E"
      }
    }
  },
  {
    "attributes": {
      "country": {
        "type": "string",
        "value": "W"
      }
    }
  },
  {
    "attributes": {
      "country": {
        "type": "string",
        "value": "E"
      }
    }
  },
  {
    "attributes": {
      "country": {
        "type": "string",
        "value": "E"
      }
    }
  },
  {
    "attributes": {
      "country": {
        "type": "string",
        "value": "E"
      }
    }
  },
  {
    "attributes": {
      "country": {
        "type": "string",
        "value": "E"
      }
    }
  },
  {
    "attributes": {
      "country": {
        "type": "string",
        "value": "W"
      }
    }
  },
  {
    "attributes": {
      "country": {
        "type": "string",
        "value": "E"
      }
    }
  }
]
col.save(data)
```

**Execute (need to wait a second for the view to catch up):** 
```
let expected = db._createStatement({ "query": "FOR s IN `v-collection` SEARCH ANALYZER(s.attributes.country.value != 'nothing', 'identity') RETURN s.attributes.country.value" })
print('Expected count: ' + expected.execute().toArray().length)

let actual = db._createStatement({ "query": "FOR s IN `v-collection` SEARCH ANALYZER(s.attributes.country.value != 'nothing' OR true == false, 'identity') RETURN s.attributes.country.value" })
print('Actual count: ' + actual.execute().toArray().length)
```

**Resulting output:**
```
Expected count: 10
Actual count: 0
```

**Comment by gnusi** [comment]
@jebbench thank you for submitting the issue, I confirm a bug. We'll address it in upcoming release(s).

**Comment by Simran-B** [comment]
The View definition does not seem to matter. I also get zero results in presence of `OR true == false`. `NOOPT(false)` does not workaround the problem.

**Comment by iurii-i-popov** [comment]
The bug is fixed. The fix will be available in next minor releases for 3.4, 3.5, and 3.6.

**Comment by maxkernbach** [comment]
Hi @jebbench,

Version 3.6.3, which includes a fix for queries that use `!= OR` in the `ANALYZER` function, has just been released.

In case this issue persists, please comment and we will reopen it.
You can find the latest version in the [download section](https://www.arangodb.com/download/).

**Comment by jebbench** [comment]
This still isn't working for me on 3.6.3 when using the EXISTS function in the AQL:
```
let actual = db._createStatement({ "query": "FOR s IN `v-collection` SEARCH ANALYZER(s.attributes.country.value != 'nothing' OR (EXISTS(s.attributes.country.value) && true == false), 'identity') RETURN s.attributes.country.value" })
```

**Comment by gnusi** [comment]
@jebbench sorry to hear that, we'll check and get back to you

**Comment by gnusi** [comment]
@jebbench fix for the issue will become a part of the next minor release.

**Comment by maxkernbach** [comment]
Hi @jebbench,

This issue should be finally fixed with version 3.6.5.

From the [Changelog](https://github.com/arangodb/arangodb/blob/4970d7642aa5658d1e22c62ec254ee14cf17c3db/CHANGELOG#L264):

> * Fixed issue #11104 case with complex condition on second branch of OR
>   operator.

Please let us know whether it works as expected now.

**Comment by jebbench** [comment]
This is still an issue for me in 3.6.6 - I've created a support ticket (OASIS-334) with a reproduction attached.
