### ISSUE TITLE
Getting "Unknown job type" after the restart of the arangodb

### ISSUE THREAD

**Issue by dagarwal82** [arangodb/arangodb#1302]
Steps to reproduce

1) Push several events to arangodb
2) Stop the arangodb
3) Start the arangodb
4) logs keep showing "WARNING Unknown job type for job 3541095535592: myCustomFunction

**Comment by pluma** [comment]
@mchacki @fceller I think the changes to Foxx in 2.5 may have delayed the registration of Foxx.queue job types until the first time the app's mount point is accessed. This would result in the above behaviour.

@dagarwal82 As a temporary workaround, could you try accessing the Foxx app(s) that defined the job type (e.g. via the admin interface)?

**Comment by dagarwal82** [comment]
I did try that. I had tried registering in setup.js (not sure if that is right or not) and going into the admin interface and executing setup.js

**Comment by pluma** [comment]
The setup script will only be executed in a single thread. So unless your copy of ArangoDB only uses a single V8 thread (default is several), that won't work.

Try putting them either in the exports or controller. Preferably the exports.

**Comment by jsteemann** [comment]
@pluma: won't this be fixed with 2.6? I remember a rewrite of the job types was planned for it. Do you think this will fix this issues, too?

**Comment by pluma** [comment]
@jsteemann no, the rewrite does not fix the existing job types, see https://github.com/arangodb/arangodb/issues/1336#issuecomment-106408761

The new job types (based on Foxx scripts) will work in 2.6, but there's no way to fix the 2.4 job types without undoing the changes introduced by @mchacki in 2.5. In a nutshell: the old job types depend on Foxx not being lazy loaded (as in 2.4), but as of 2.5 Foxx is lazy loaded again.

**Comment by jsteemann** [comment]
@pluma: but once 2.6 is out and existing pre-2.6 job types are (manually) fixed, the problem should be fixed, right?

**Comment by pluma** [comment]
The 2.6 job types will not suffer from this problem, no. But there's no way to convert them automagically. The job types need to be rewritten manually (except for those in the app store -- those I will rewrite myself) and any queued jobs need to be converted manually as well.

**Comment by pluma** [comment]
A workaround has been implemented in devel and will be backported to 2.5. See 697ffb8d5880cc69b47d0c300d38661efc8a21d3
