### ISSUE TITLE
Single Machine Cluster Setup in Windows

### ISSUE THREAD

**Issue by yammelvin** [arangodb/arangodb#1305]
I tried to follow the cluster setup according to the documentation in Windows 7.

However I encounter the following error when launching the cluster:
flag provided but not defined: -initial-cluster-state

I'm using ArangoDB version 2.5.1

Can anybody help?

Thanks.

Melvin

**Comment by fceller** [comment]
This is a bug. The installer contains a wrong ETCD version.

**Comment by fceller** [comment]
@yammelvin this should be fixed in 2.5.5. Can you confirm?

**Comment by yammelvin** [comment]
Tried 2.5.5.
No more "flag provided but not defined: -initial-cluster-state" error.

But cluster still cannot be launched.
There seem to be runtime error: invalid memory address.
Below is the log:

```
tcp://127.0.0.1:8529
tcp://127.0.0.1:8529
tcp://127.0.0.1:8529
tcp://127.0.0.1:8529
tcp://127.0.0.1:8529
tcp://127.0.0.1:8529
tcp://127.0.0.1:8529
2015/06/03 09:26:19 etcd: listening for peers on http://127.0.0.1:7001
2015/06/03 09:26:19 etcd: listening for client requests on http://127.0.0.1:4001
2015/06/03 09:26:19 etcdserver: datadir is valid for the 2.0.1 format
2015/06/03 09:26:19 etcdserver: name = agentarango4001
2015/06/03 09:26:19 etcdserver: data dir = d:\ArangoDB-2.5.5-win32\var\lib\arangodb\cluster\agentarango4001
2015/06/03 09:26:19 etcdserver: member dir = d:\ArangoDB-2.5.5-win32\var\lib\arangodb\cluster\agentarango4001/member
2015/06/03 09:26:19 etcdserver: heartbeat = 100ms
2015/06/03 09:26:19 etcdserver: election = 1000ms
2015/06/03 09:26:19 etcdserver: snapshot count = 10000
2015/06/03 09:26:19 etcdserver: advertise client URLs = http://127.0.0.1:4001
2015/06/03 09:26:19 etcdserver: initial advertise peer URLs = http://127.0.0.1:7001
2015/06/03 09:26:19 etcdserver: initial cluster = agentarango4001=http://127.0.0.1:7001
2015-06-03T01:26:19Z [3216] INFO Starting agent...
2015/06/03 09:26:19 etcdserver: start member e52ada62956ff923 in cluster a9efa5de7f8fc772
2015/06/03 09:26:19 raft: e52ada62956ff923 became follower at term 0
2015/06/03 09:26:19 raft: newRaft e52ada62956ff923 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2015/06/03 09:26:19 raft: e52ada62956ff923 became follower at term 1
2015/06/03 09:26:19 etcdserver: added local member e52ada62956ff923 [http://127.0.0.1:7001] to cluster a9efa5de7f8fc772
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x55deab]

goroutine 7 [running]:
sync/atomic.StoreUint64(0x11a7a6ec, 0x1, 0x0)
        c:/go/src/sync/atomic/asm_386.s:196 +0xb
github.com/coreos/etcd/etcdserver.(*EtcdServer).apply(0x11a7a6c0, 0x11a548d0, 0x1, 0x1, 0x11ab6540, 0x0, 0x0, 0x0)
        C:/Go/src/github.com/coreos/etcd/etcdserver/server.go:704 +0x1ee
github.com/coreos/etcd/etcdserver.(*EtcdServer).run(0x11a7a6c0)
        C:/Go/src/github.com/coreos/etcd/etcdserver/server.go:430 +0xe1f
created by github.com/coreos/etcd/etcdserver.(*EtcdServer).start
        C:/Go/src/github.com/coreos/etcd/etcdserver/server.go:298 +0x230

goroutine 1 [runnable]:
github.com/coreos/etcd/etcdmain.Main()
        C:/Go/src/github.com/coreos/etcd/etcdmain/etcd.go:102 +0x86c
main.main()
        C:/etcd-2.0.9/main.go:29 +0x1e

goroutine 8 [runnable]:
github.com/coreos/etcd/etcdserver.(*EtcdServer).Do(0x11a7a6c0, 0x133a60, 0x11a5a900, 0xb5430001, 0x234db706, 0x73bf90, 0x3, 0x11a54b70, 0x26, 0x11a5c460, ...)
        C:/Go/src/github.com/coreos/etcd/etcdserver/server.go:496 +0x4dd
github.com/coreos/etcd/etcdserver.(*EtcdServer).publish(0x11a7a6c0, 0x2a05f200, 0x1)
        C:/Go/src/github.com/coreos/etcd/etcdserver/server.go:658 +0x2a7
created by github.com/coreos/etcd/etcdserver.(*EtcdServer).Start
        C:/Go/src/github.com/coreos/etcd/etcdserver/server.go:279 +0x4b

goroutine 9 [runnable]:
github.com/coreos/etcd/etcdserver.(*EtcdServer).purgeFile(0x11a7a6c0)
        C:/Go/src/github.com/coreos/etcd/etcdserver/server.go:309 +0x34c
created by github.com/coreos/etcd/etcdserver.(*EtcdServer).Start
        C:/Go/src/github.com/coreos/etcd/etcdserver/server.go:280 +0x60

goroutine 10 [IO wait]:
net.(*pollDesc).Wait(0x11a74450, 0x72, 0x0, 0x0)
        c:/go/src/net/fd_poll_runtime.go:84 +0x42
net.(*ioSrv).ExecIO(0x11a6e490, 0x11a743b8, 0x745d98, 0x8, 0x11a6e720, 0x11a74700, 0x0, 0x0)
        c:/go/src/net/fd_windows.go:188 +0x265
net.(*netFD).acceptOne(0x11a74380, 0x11a74460, 0x2, 0x2, 0x11a743b8, 0x0, 0x0, 0x0)
        c:/go/src/net/fd_windows.go:558 +0x3ee
net.(*netFD).accept(0x11a74380, 0x0, 0x0, 0x0)
        c:/go/src/net/fd_windows.go:585 +0x119
net.(*TCPListener).AcceptTCP(0x11a6e4a0, 0x0, 0x0, 0x0)
        c:/go/src/net/tcpsock_posix.go:234 +0x48
net.(*TCPListener).Accept(0x11a6e4a0, 0x0, 0x0, 0x0, 0x0)
        c:/go/src/net/tcpsock_posix.go:244 +0x48
github.com/coreos/etcd/pkg/transport.(*rwTimeoutListener).Accept(0x11ab2520, 0x0, 0x0, 0x0, 0x0)
        C:/Go/src/github.com/coreos/etcd/pkg/transport/timeout_listener.go:44 +0x5e
net/http.(*Server).Serve(0x11a5a980, 0x133438, 0x11ab2520, 0x0, 0x0)
        c:/go/src/net/http/server.go:1728 +0x7b
github.com/coreos/etcd/etcdmain.serveHTTP(0x133438, 0x11ab2520, 0x1339a0, 0x11ab6520, 0xd964b800, 0x45, 0x0, 0x0)
        C:/Go/src/github.com/coreos/etcd/etcdmain/http.go:36 +0x170
github.com/coreos/etcd/etcdmain.func┬╖005(0x133438, 0x11ab2520)
        C:/Go/src/github.com/coreos/etcd/etcdmain/etcd.go:198 +0x4a
created by github.com/coreos/etcd/etcdmain.startEtcd
        C:/Go/src/github.com/coreos/etcd/etcdmain/etcd.go:199 +0x14b5

goroutine 11 [IO wait]:
net.(*pollDesc).Wait(0x11a746f0, 0x72, 0x0, 0x0)
        c:/go/src/net/fd_poll_runtime.go:84 +0x42
net.(*ioSrv).ExecIO(0x11a6e490, 0x11a74658, 0x745d98, 0x8, 0x11a6e728, 0x11a748c0, 0x0, 0x0)
        c:/go/src/net/fd_windows.go:188 +0x265
net.(*netFD).acceptOne(0x11a74620, 0x11a747e0, 0x2, 0x2, 0x11a74658, 0x0, 0x0, 0x0)
        c:/go/src/net/fd_windows.go:558 +0x3ee
net.(*netFD).accept(0x11a74620, 0x0, 0x0, 0x0)
        c:/go/src/net/fd_windows.go:585 +0x119
net.(*TCPListener).AcceptTCP(0x11a6e4d8, 0x1, 0x0, 0x0)
        c:/go/src/net/tcpsock_posix.go:234 +0x48
net.(*TCPListener).Accept(0x11a6e4d8, 0x0, 0x0, 0x0, 0x0)
        c:/go/src/net/tcpsock_posix.go:244 +0x48
github.com/coreos/etcd/pkg/transport.(*keepaliveListener).Accept(0x11a6e4e0, 0x0, 0x0, 0x0, 0x0)
        C:/Go/src/github.com/coreos/etcd/pkg/transport/keepalive_listener.go:48 +0x5e
net/http.(*Server).Serve(0x11a5a9c0, 0x133458, 0x11a6e4e0, 0x0, 0x0)
        c:/go/src/net/http/server.go:1728 +0x7b
github.com/coreos/etcd/etcdmain.serveHTTP(0x133458, 0x11a6e4e0, 0x133a88, 0x11a52aa0, 0x0, 0x0, 0x0, 0x0)
        C:/Go/src/github.com/coreos/etcd/etcdmain/http.go:36 +0x170
github.com/coreos/etcd/etcdmain.func┬╖006(0x133458, 0x11a6e4e0)
        C:/Go/src/github.com/coreos/etcd/etcdmain/etcd.go:206 +0x6d
created by github.com/coreos/etcd/etcdmain.startEtcd
        C:/Go/src/github.com/coreos/etcd/etcdmain/etcd.go:207 +0x15c6
2015-06-03T01:26:21Z [3216] INFO Sending  to agency...
2015-06-03T01:26:21Z [3216] INFO Sending /arango to agency...
2015-06-03T01:26:21Z [3216] INFO Sending /arango/Target to agency...
2015-06-03T01:26:21Z [3216] INFO Sending /arango/Target/Lock to agency...
```

**Comment by fceller** [comment]
@dothebart can you check this under Windows?

**Comment by dothebart** [comment]
Yes, reproduceable.

**Comment by fceller** [comment]
Done in 2.6

**Comment by dothebart** [comment]
verified fixed with 2.6
