### ISSUE TITLE
web frontend authentication issues

### ISSUE THREAD

**Issue by legikaloz** [arangodb/arangodb#1351]
I turned authentication on in /etc/arangodb/arangod.conf with disable-authentication = no (it was "yes" by default, but the manual says the default value is false)
Added some user in arangosh (users were reloaded, even db restarted too), and tried to login to:
https://myip:8530/_db/_system/_admin/aardvark/index.html
A HTTP authentication window pops out or sometimes a login form, but i get this message: `{"error":"unauthorized"}` I get this immediately after a page reload, or server restart(!) too. After a fresh server restart with this shorter link https://myip:8530/_db/_system/ I get the auth window.
I tried to clear cache, cookies, use incognito window, another browser (Firefox 38, Chromium 43)
There are no problems to login with arangosh.

**Comment by jsteemann** [comment]
I guess you have been using 2.6-alpha2, or did you compile from source?

**Comment by legikaloz** [comment]
Sorry I left it. Yes I'm using 2.6-alpha2

**Comment by jsteemann** [comment]
Thanks for confirming. I think this is something we have already fixed after alpha2 came out, but we'll revalidate. Which was the browser you used before you switch to others (you mentioned you switch to Firefox 38 and Chromium 43)?

**Comment by legikaloz** [comment]
I think the first attempt was made with Chrome 43 beta, then Chromium 43,
finally with Firefox.
2015. máj. 28. 18:56 ezt írta ("Jan" <notifications@github.com>):

**Comment by pluma** [comment]
@legikaloz Could you check whether the issue persists in the latest pre-release?

**Comment by legikaloz** [comment]
Checked, it seems ok in 2.6-alpha3
