### ISSUE TITLE
Swagger-UI behaves erratically

### ISSUE THREAD

**Issue by dothebart** [arangodb/arangodb#1387]
As discovered by Gareth Cox, 
https://groups.google.com/forum/#!topic/arangodb/hdyn7ZrB4ms
This generated app :
https://docs.google.com/viewer?a=v&pid=forums&srcid=MDA1Njc3NDI0NzkxMDA3MjI4MDEBMDUwNjk4NTI2MzAwMzM1MjI3NjUBaGlCR2VhdklCLUVKATAuMQEBdjI&authuser=0

Will send an empty post body when trying to post to nodeTypes in the swagger UI:
{
  "name": "Domain",
  "description": "Domains",
  "deleted": false
}
(reproduced with IceWeasel 31.6.0 from debian stable)
As the zip was produced on a mac, this may be related to #1368

**Comment by pluma** [comment]
That's amazing. I suspect this is an issue with Swagger 2.0 or the Swagger JSON generating code.

I doubt #1368 is related as that was not actually platform-specific and instead had to do with files not being included in the distribution packages of ArangoDB.

**Comment by fceller** [comment]
@pluma has this been fixed in 2.7.0?

**Comment by pluma** [comment]
@fceller I'm not sure. @dothebart Didn't you update Swagger as part of the API docs changes? Could you check whether this issue persists in devel?

**Comment by dothebart** [comment]
the generated swagger json: https://gist.github.com/60f6ca4cd0b38181d49e

**Comment by dothebart** [comment]
the fixed file https://gist.github.com/pluma/5a0a62e11ee38e47bed9#file-swagger-json still reproduces this issue.

**Comment by pluma** [comment]
Reassigning to @dothebart because there's nothing we can do until Swagger addresses this and he's the author of the Swagger issue.

**Comment by pluma** [comment]
We should use this issue to track all swagger-related problems as Swagger-UI also seems to have problems dealing with some of the spec-compliant output Foxx produces now. We're still waiting for an upstream fix to Swagger-UI.

**Comment by Simran-B** [comment]
General swagger issue: routes can't be overloaded, i.e. the same endpoint can not be defined twice for different post bodies. It is unlikely to be solved upstream. My guess is that they don't want to break backward compatibility of swagger JSON, which uses routes as keys and does thus not support multiple definitions (same key).

The current workaround is to add an anchor to the route: `_api/do-something#something`, `_api/do-something#else`

**Comment by dothebart** [comment]
The issue (https://github.com/swagger-api/swagger-ui/issues/1691) has been fixed upstream; we should update swagger and revalidate.

**Comment by dothebart** [comment]
maybe @pluma , @hkernbach or @mpv1989 can do this

**Comment by jsteemann** [comment]
Confirmed to be fixed in 3.1.27 and 3.2
