### ISSUE TITLE
Document values with null character truncated with 2.6.2 on Windows

### ISSUE THREAD

**Issue by wiredprairie** [arangodb/arangodb#1409]
In ArangoDB 2.5.2 (and maybe earlier), we had written code that relied on a value within a document allowing NULL characters.

In ArangoDB 2.6.1+ on Windows, it appears that the NULL character is acting as the string terminator, even when there may be more string data. How can we restore the previous behavior? 

For example, if the value is `"value\u0000SubValue1\u0000SubValue2"`, the newer version unfortunately truncates:

    2.5.2 => "value\u0000SubValue1\u0000SubValue2"
    2.6.2 => "value"

We are using the NULL to act as a delimiter as we know that is the one character that won't appear within the sub-strings we're using.

Here are the steps for reproducing the issue from the shell on Windows.

    arangosh [demo]> db._create("SO")
    [ArangoCollection 848312398088, "SO" (type document, status loaded)]
    arangosh [demo]> db.SO.save({ "v":"a\u0001b"})
    {
      "_id" : "SO/848317640968",
      "_rev" : "848317640968",
      "_key" : "848317640968"
    }
    arangosh [demo]> db.SO.document("SO/848317640968")
    {
      "v" : "a\u0001b",
      "_id" : "SO/848317640968",
      "_rev" : "848317640968",
      "_key" : "848317640968"
    }

That one worked as it was the `\u0001` character. Here's where using `\u0000` does not work anymore:

    arangosh [demo]> db.SO.save({ "v":"a\u0000b"})
    {
      "_id" : "SO/848320262408",
      "_rev" : "848320262408",
      "_key" : "848320262408"
    }
    arangosh [demo]> db.SO.document("SO/848320262408")
    {
      "v" : "a",      // the rest of the value has been truncated
      "_id" : "SO/848320262408",
      "_rev" : "848320262408",
      "_key" : "848320262408"
    }

I posted the issue on [StackOverflow](http://stackoverflow.com/questions/31213975/using-a-null-within-a-document-value) originally. One response was that this functionality still worked on Linux (but we are using Windows only, so that didn't help us address the issue).

**Comment by CoDEmanX** [comment]
It can't be related to #1383 if it occurs in 2.6.1 already (and would be strange anyway). So there must have been a change to string handing somewhere else. A JSON encoded binary zero shouldn't be interpreted as string termination byte of course, strings should be handled in a binary-safe fashion.

If you need to store multiple character sequences in an attribute, you should consider an array however. It will solve the  of a separation character that mustn't appear within any element:

    {attr: ["value", "subValue1", " subValue2"]}

You can simply do this as a preprocessing step, e.g. `"Foo\0Bar".split("\0")` in JavaScript.

**Comment by jsteemann** [comment]
I submitted a fix for this in the 2.6 branch, which will become release version 2.6.3 eventually.

Please note that using NUL bytes inside attribute values does not seem to have worked since at least April 2014 under some circumstances, meaning it may not have worked in 2.5, and not even 2.4 and 2.3.

The *circumstances* I am referring to are how the document was retrieved (JavaScript functions inside the server or via HTTP API, AQL or CRUD operations) and whether or not the document was saved in ShapedJson format or not. 

I was able to reproduce the issue with 2.5 & 2.6 under Linux as well in the following cases when the document was retrieved via the HTTP REST API and using a single document read, i.e. via HTTP GET `/_api/document/<collection>/<key>`. 

Here's how to reproduce:
```js
db._create("SO");
db.SO.save({ "v": "a\u0000b", _key: "b" });
```

And then from inside the ArangoShell:
```js
db.SO.document("b")
```
This returns the truncated value:
```js
{ 
  "v" : "a", 
  "_id" : "SO/b", 
  "_rev" : "4124146417077", 
  "_key" : "b" 
}
```

**Comment by wiredprairie** [comment]
We tested and the C# version works now, but using a simple REST client written in Node, we're still seeing the truncation. Is that expected?

**Comment by jsteemann** [comment]
It shouldn't have anything to do with the client driver, but this was a server issue.
Are you sure the Node client is calling the same ArangoDB as the C# version? 
And which version of ArangoDB are you using?

**Comment by wiredprairie** [comment]
The ArangoDB server is hosted locally on a workstation, so it's definitely
the same version being used by both clients. The developer doing the
testing right now has 2.6.4 installed on her machine and her code is using
AQL. Maybe it's a separate issue.

**Comment by wiredprairie** [comment]
Here's what's being sent in the Node example:

    var query: string = "";
    query += "UPSERT { a: @allKeys } ";
    query += "INSERT { a: @allKeys, v: @newValue" + keyExample + " } ";
    query += "UPDATE { v: @newValue } ";
    query += "IN @@coll";

The body of my HTTP POST request is this

    "{"query":"UPSERT { a: @allKeys } INSERT { a: @allKeys, v: @newValue, s1: @s1 } 
    UPDATE { v: @newValue } IN @@coll","batchSize":1,"count":false,"ttl":1,
    "bindVars":{"@coll":"X","s1":1,"allKeys":"(1)","newValue":"\u0000"}}"

The response status code comes back as `201` (success) and the document is there but the `v` property is empty instead of `“\u0000”` like it should be.

**Comment by jsteemann** [comment]
What version of ArangoDB are you using?

**Comment by wiredprairie** [comment]
Unless I'm misunderstanding your question, as I'd mentioned the developer
doing the testing has 2.6.4 installed on her workstation (Windows 8.1).

**Comment by jsteemann** [comment]
Sorry, I overlooked it. Yes, that version is what I was after.

**Comment by jsteemann** [comment]
From what I found yesterday night, it seems that attribute values containing the NUL byte may still be truncated when used from AQL queries. I think it's fixed in devel now by the following commit: https://github.com/arangodb/arangodb/commit/4c373860b6bf0679da4472de1c7ef1a51ad4548b
The commit is not very small in size, so I have to check how easy it is to backport it to 2.6.

**Comment by jsteemann** [comment]
The fix has been backported to 2.6 and will be included in the next release.

**Comment by CoDEmanX** [comment]
There are still issues regarding null bytes it seems, I tried the following in 2.8 beta on Windows:

```js
for doc in test
filter doc.val == "\u0000nope"
return doc

/* These documents should NOT be returned!
[
  {
    "val": "\u0000zero\u0000",
    "_id": "test/42192784985",
    "_rev": "42192784985",
    "_key": "42192784985"
  },
  {
    "val": "\u0000\r\nnew line",
    "_id": "test/inary",
    "_rev": "42175352409",
    "_key": "inary"
  }
]
*/

for doc in test
filter substring(doc.val, 0, 5) == "\u0000zero"
return substring(doc.val, 0, 5)

/* empty result, although one document should had been returned!
[]
If you remove the filter statement, "\u0000zero" will be returned,
so why doesn't it match?
*/

for doc in test
filter substring(doc.val, 0, 1) == "\0"
return doc

/* wrong document(s) returned, it does not start with a null byte (\0), but a literal 0:
[
  {
    "val": "0\r\nxxx",
    "_id": "test/42049261145",
    "_rev": "42169323097",
    "_key": "42049261145"
  }
]
*/
```

**Comment by CoDEmanX** [comment]
The following fails in Aardvark, but not arangosh (both incorrectly return nothing):

```js
for doc in test
filter substring(doc.val, 0, 1) == @zero
return doc

// bind params:
{"zero": "\0"}
```
> Query error: Could not parse bind parameters.

**Comment by jsteemann** [comment]
Thanks, should all be fixed now. 

Regarding the bottommost one in aardvark ("Query error: Could not parse bind parameters"): this is actually correct, as bind parameters in the web interface need to be valid JSON values, and `"\0"` is no valid JSON string. It will work (now) when using the proper JSON string value `"\u0000"`

**Comment by CoDEmanX** [comment]
You're right about `\0`, I mixed up the JSON and JS specs. It works in arangosh because it's JS, but it's indeed invalid JSON.

1 and 2 are fixed! 3 is still the same, but expectable since `\0` is not a valid escape sequence in JSON. A single reverse solidus is silently ignored, `\3` returns documents whose val attribute starts with `3` and so on. `\u0000` returns the correct document, so everything is apparently resolved.

**Comment by jsteemann** [comment]
`LIKE` also fixed now. It had a special handling of its parameters because internally they were passed into ICU.

**Comment by CoDEmanX** [comment]
Works silky smooth, thank you!
