### ISSUE TITLE
Graph viz tool cannot filter integer fields

### ISSUE THREAD

**Issue by codem4ster** [arangodb/arangodb#1410]
I have an integer field in my collection. When I try to filter the graph with this field in graph viz, it doesn't show any node nor edge.

**Comment by fceller** [comment]
@codem4ster has this been fixed in 2.7.0?

**Comment by hkernbach** [comment]
No this is not fixed. Also all values of edges or vertices can only be edited as strings in graph viewer.

**Comment by codem4ster** [comment]
Additionally, graph viewer is not user friendly and usable. I think that this section needs a complete rewrite. I love arangodb in all aspects except this. May be you can look at neo4j's graph viewer or another graph viewing tools.  I'm writing some of the non-user-friendly points below that I saw on the graph viewer. 
- (Most Important) I cannot generate graph view by aql.
- I cannot search a specific collection's field. Ex: card_number.code. Sometimes I have 2 collections in the same graph with the same field name. I want to filter with card_number's codes not with the phone_number.code. But the filter is only works with field name.
- Coloring also must be done by collections. I want to change color of card_number collection nodes to blue and change phone_number collection nodes to red. 
- Node naming must be done by collections also.  I might change card_number nodes' visible value to code field and phone_number collection's visible value to number may be.
- Same cases are valid for edges too. 
- As extras, edges may have types like dotted, dashed etc...
- Grouping is a good feature but I cannot figure out that's logic. How is that grouping nodes? I think; It can group same collection's nodes together and we might be able to make subgroup by same field values.

If these features are not applicable, then I should be able to use another external tool or service, but I don't know is arangodb supports this.

**Comment by hkernbach** [comment]
We are now collecting all issues regarding the graph viewer in a new ticket: #1595
