### ISSUE TITLE
Search box no longer in Source view in Aardvark as of 2.6

### ISSUE THREAD

**Issue by pluma** [arangodb/arangodb#1446]
There used to be a search box in the "Source" tab of the document detail view triggered if you press Ctrl+F (probably Cmd+F on OSX). As of 2.6 that seems to be gone. I'm suspecting we updated the ACE editor at some point and missed a flag or accidentally removed the key binding (I recall an earlier issue where we removed some key bindings).

This wouldn't be much of a problem but the browser's "Find in page" feature can only search the parts of the source code that is presently visible, rendering it pretty much useless in any scenario where you'd want to use search.

**Comment by hkernbach** [comment]
fixed (updated jsoneditor lib): bb963fe8c0e57bfa092c6910896de7d4ef0e6407

**Comment by pluma** [comment]
This doesn't seem to have been fixed in 2.6.9.

**Comment by jsteemann** [comment]
Some minor issues persist even after the update: 
* after clicking into the search box, the cursor is not visible. It is unclear to the user that the cursor is actually in the search box.
* typing a non-existing attribute name into the search box will clear all output. So far, so good. However, when removing the attribute name from the search box (so the search box is empty), the document attributes don't show up again. It is then necessary to type some valid attribute name to make them re-appear. This sucks.

**Comment by pluma** [comment]
Just to be clear: I'm talking about search in source mode, not in tree mode.

**Comment by jsteemann** [comment]
I was talking about the one in tree mode. There isn't (yet?) a search box in source mode in current 2.7.

**Comment by pluma** [comment]
Exactly. There *was* a search box in 2.5 and it disappeared in 2.6. Because the editor doesn't actually render the entire source tree into the DOM, the browser's "find" command doesn't work for documents longer than ~20 lines.

**Comment by hkernbach** [comment]
The search box at the source view is back again. You have to enable it using CTRL+F or CMD+F (Mac). Hitting that shortcuts again opens a replace dialog.

**Comment by hkernbach** [comment]
@jsteemann 

1. after clicking into the search box, the cursor is not visible. It is unclear to the user that the cursor is actually in the search box.

- cannot reproduce this issue. tested on os x chrome,firefox and safari.

2. typing a non-existing attribute name into the search box will clear all output. So far, so good. However, when removing the attribute name from the search box (so the search box is empty), the document attributes don't show up again. It is then necessary to type some valid attribute name to make them re-appear. This sucks.

- added event to check if box is empty or not. when value is empty, all attributes will expand.

**Comment by fceller** [comment]
@hkernbach has this been fixed in 2.7.0?

**Comment by hkernbach** [comment]
seems to be a bug in firefox (seen in ubuntu). can't fix
