### ISSUE TITLE
Arango 2.5.* (Windows) becomes unresponsive

### ISSUE THREAD

**Issue by rossmills99** [arangodb/arangodb#1466]
In our development environments we have ArangoDB 2.5.* installed (we do intend to move to using ArangoDB 2.6 when we can but this may not be for some time due to the breaking API changes involved).  Arango is installed on Windows 7 or Windows 8 machines, running as a Windows service. 

We make extensive use of AQL queries submitted using the Cursor API, the Document API and the Edge API.  Our application database is built around a graph with several Document and Edge collections. We have implemented a couple of custom AQL functions which are specific to our application.

We have found during development that the ArangoDB service sometimes becomes unresponsive, requiring it to be restarted. Unfortunately we have no insight into what might be causing this. 

Any recommendations on how to figure out what is causing this would be appreciated.

**Comment by jsteemann** [comment]
When it becomes unresponsive, is there any observable I/O or CPU activity for the ArangoDB process?

**Comment by dothebart** [comment]
Recommendation No1: please change 2.5.* to 2.5.7 since we have a fix in there which is especially important for Windows environments (but that incident usually would not hang).
To get further informations about incidents happening (beyound cpu usage), we would need a minidump of such a hanging process. Since we only started using a symobl server very recently, at least 2.5.6 but better 2.5.7 builds would be required. 

On the procedure of aquiring such a minidump: 
Open the windows task-manager, change its view to 'More details', identify the hanging arangod process. open the context of the task manager over the line with the 'arangod' or 'arangodb' and select 'Create Dump File'
Once that is finished a Dialog appears with the URL to the file created. Its important to keep the dialog open until you locate it in explorer, since its a hidden folder you need to enter the URL in the location bar by hand. 
The file may be huge, so please compress it (i.e. with 7zip) and upload it somewhere ala dropbox so we can download it.
Then we may analyze the dump file and find the problem.

**Comment by rossmills99** [comment]
Thanks, the APB is in, so when someone experiences the issue again I will report back

**Comment by dothebart** [comment]
ok, I think the incident is solved; open a new or reopen if you want to continue on this.

**Comment by rossmills99** [comment]
I am still seeing Arango crash occasionally. It now seems to happen regularly during a run of some automated tests which hit the database.  This process is not hanging, but the Windows service itself has stopped completely.

I notice the issue https://github.com/arangodb/arangodb/issues/1406 which sounds like it might be the same thing, should I continue commenting here or shall I add to that issue?

**Comment by jsteemann** [comment]
Looking at the issue descriptions, it sounds like the two issues are related. But that can only be confirmed once the cause is found (and fixed). If you have any further information on how to reproduce the issue, that would be very helpful.

**Comment by rossmills99** [comment]
OK, I have enabled logging to file on the test VM, if (when) it crashes again I can get you the log files. 

In the meantime here are Windows event log entries that seem relevant:

Source: ArangoDB
````
The description for Event ID 256 from source ArangoDB cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

Unhandled exception: -1073741819 - will crash now.
C:\b\ArangoDB-2.5.7\arangod\RestServer\WindowsServiceUtils.cpp
unhandledExceptionHandler
527
````

Source: Application Error
````
Faulting application name: arangod.exe, version: 2.5.7.232, time stamp: 0x55bf3f47
Faulting module name: arangod.exe, version: 2.5.7.232, time stamp: 0x55bf3f47
Exception code: 0xc0000005
Fault offset: 0x00000000003f4df9
Faulting process id: 0x690
Faulting application start time: 0x01d0fab5cf4cf0c3
Faulting application path: C:\Program Files\ArangoDB 2.5.7\bin\arangod.exe
Faulting module path: C:\Program Files\ArangoDB 2.5.7\bin\arangod.exe
Report Id: 2169147d-682d-11e5-aadf-000c2995cd22
````

Source: Service Control Manager
````
The ArangoDB service terminated unexpectedly.  It has done this 1 time(s).
````

**Comment by jsteemann** [comment]
The exception code means that there was an access violation, and the program crashed. More information, including stack traces from the crash location, may be revealed by writing a core dump (Linux) or a mini dump (Windows). 
To have a Windows ArangoDB write a mini dump when it crashes, some manual work is needed as described [here](https://github.com/arangodb/arangodb/blob/devel/README_maintainers.md#coredump-generation).

So far and without having any further information about the crash, we can only guess what the cause is. However, the issue may be related to #1406. We believe that this problem is triggered from inside of V8's garbage collection, at least we have seen a few crashes come from there on Windows platforms. ArangoDB 2.7 uses a newer V8 version that 2.6 & 2.5, and does not seem to have this problem. So we are positive that this issue will be resolved by moving to 2.7.

A stable release of 2.7 is not out now, but it should be available soon. You mentioned that API changes in 2.6 kept you from upgrading to 2.6, and so potentially will also keep you from moving to 2.7. Can you elaborate a bit on what changes are problematic? AFAIK the return values of some graph functions changed in 2.6, but I don't remember more severe issues.

**Comment by rossmills99** [comment]
Yeah it's those return values in 2.6 which would cause a problem, I'm sure we could adapt to them relatively easily although we do use the graph functions quite a lot.  If the issue is absolutely resolved by moving to 2.7 this would obviously become a priority for us...

**Comment by jsteemann** [comment]
It's difficult to confirm that 2.7 will definitely fix **this** issue. 

The problem is that all we know is that from time to time the server crashed on Windows with an access violation exception, but without a core/mini dump we can only guess what actually caused it. 
It's likely that this is totally related to the garbage collection issue I mentioned above and from the other referenced issue, but without further details this is only guessing.

**Comment by rossmills99** [comment]
Understood, I will set up procdump and see if we can get a minidump next time it crashes

**Comment by jsteemann** [comment]
Thanks!

**Comment by dantomosoiu** [comment]
Hello,

Here is an archive of a non-responsive arangod.exe dump: https://www.dropbox.com/sh/jv77f8nq74ot5hj/AAAX-07DV0VG44dXjFL9p60Ua?dl=0

The process was showing 0% CPU usage, but I forgot to check I/O.

Hope this helps,
Dan

**Comment by dantomosoiu** [comment]
Also, not sure how relevant, but the service wouldn't stop when manually requested from the Services window. I had to kill the process from the task manager to be able to restart it.

**Comment by rossmills99** [comment]
Was just trying out 2.7 now and Arango service crashed after a short time (20 minutes).  The following event logs: 

````
The description for Event ID 256 from source ArangoDB cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

Unhandled exception: -1073741819 - will crash now.
C:\b\ArangoDB-2.7.0\arangod\RestServer\WindowsServiceUtils.cpp
unhandledExceptionHandler
528
````

````
Faulting application name: arangod.exe, version: 2.7.0.6, time stamp: 0x5617caa7
Faulting module name: arangod.exe, version: 2.7.0.6, time stamp: 0x5617caa7
Exception code: 0xc0000005
Fault offset: 0x00000000004bcfc9
Faulting process id: 0x2d90
Faulting application start time: 0x01d104f0c2bda11d
Faulting application path: C:\Program Files\ArangoDB 2.7.0\bin\arangod.exe
Faulting module path: C:\Program Files\ArangoDB 2.7.0\bin\arangod.exe
Report Id: d272579b-70ed-11e5-9720-b888e306083c
````

**Comment by rossmills99** [comment]
I have not been able to produce a dump yet, I frequently see the line:

` Exception: E06D7363.?AVException@basics@triagens@@`

printed to the console where I have procdump running. Is this normal?

**Comment by dothebart** [comment]
Exceptions are thrown internally as program control flow; i.e. if you have a syntax error in AQL it will throw an exception to abort the execution of this query. 
However, the exception is caught in the executing layer, and translated into an error message for the user. 
As you can see, these exceptions are classes, which are used to carry more informations.
Its a feature of procdump to print out that they occur - but as long as the program handles them, its intended behaviour.
If an exception isn't handled, a crash will occur, and procdump will write the dump file.

**Comment by dothebart** [comment]
Ok, @dantomosoiu I had a look at that lockup dump you provided. From the analysis we have several questions about the situation the server could be encountering (we can't see js stackframes). 

We see 3 threads attempting to query an edge colletion. One of the 3 seems to be loading the collection (so its not yet loaded?) 2 of the others are waiting in an earlier state to get access to it.

A 4th thread is probably doing something in js like:
db.EBomPartOf.<something>? (where db is the database object)

We can't get the name of the edge collections from the 3 edge queries from the debugger. So we to know need a little more about your usecase.

Could EBomPartOf actually be an edge collection? E* would sugest that... 

Do you unload or drop an edge collection somewhere else? Is this the first access to a collection after an import? Or is the server in shutdown progress before you created the core dump?

**Comment by dantomosoiu** [comment]
EBomPartOf is an edge collection, yes. If it helps to figure out their types, here is a screenshot of all our collections: 
![cols](https://cloud.githubusercontent.com/assets/1804374/10612254/e6e61a72-7747-11e5-9b9e-d3bc70a15dcf.jpg)

It is possible that the database was recently recreated, yes, so there is a chance some of the collections access might have been done for the first time at that moment. However there shouldn't have been any unloading/drops caused as part of current queries (the database deployment was finished), nor was the server in shutdown.

Do you think manually loading the collections after a deployment something we should consider, in order to avoid having to wait for that at query time ? (Is that even possible, aside from just running a query on the collection ?)

Please let me know if there's anything else I can help with.

Regards,
Dan

**Comment by dothebart** [comment]
Yes, loading collections manually after the regular startup could be helpfull to circumvent this and give you calculateable response times from the start. Once your data amount rises, database warmup is a good thing to do after a maintainance window.

**Comment by rossmills99** [comment]
Finally managed to capture a dump after Arango 2.7 crashed, windows event log shows:

```
Faulting application name: arangod.exe, version: 2.7.0.6, time stamp: 0x5617caa7
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x000000000fdb8e42
Faulting process id: 0x64c
Faulting application start time: 0x01d1068508770502
Faulting application path: C:\Program Files\ArangoDB 2.7.0\bin\arangod.exe
Faulting module path: unknown
Report Id: 4d609fc4-78f8-11e5-aadf-000c2995cd22
```

Dump file here:
https://www.dropbox.com/s/avwe7p9qb10xuaw/arangod.exe_151022_210511.zip?dl=0

**Comment by jsteemann** [comment]
@dantomosoiu : the dump helped us to identify an issue that can have caused a deadlock on Windows, in situations when one thread was running queries on a collection and another thread dropped or unloaded the collection. This issue has been fixed in 2.5, 2.6, 2.7 branches today. The issue fixed may have caused deadlocks on Windows but shouldn't have led to crashes. As this issue is about different problems by now, I won't close it.

**Comment by dothebart** [comment]
We tried hard to work on potential windows issues during the 2.8 release cycle. Other ArangoDB windows users said it has been running stable for them now. Please upgrade to 2.8. If the problem persists for you, it would be great if we could get access to an installation reproducing this under NDA.

Else I think we can close this soon.

**Comment by dothebart** [comment]
@dantomosoiu sorry for making the connection late, this is probably related to https://groups.google.com/d/msg/arangodb/HmN1_0lQ23o/-IpMuJtQAwAJ ? ;-)

**Comment by dantomosoiu** [comment]
No worries :)

I've been working with 2.8 since it's been released, and had no problems so far. 
I think this can be closed, if any problems come up I'll let you know.

Thanks,
Dan
