### ISSUE TITLE
Wrong count returned in AQL query using an AnragoSearch view

### ISSUE THREAD

**Issue by Darkheir** [arangodb/arangodb#15545]
## My Environment

* __ArangoDB Version__:        3.7.9
* __Deployment Mode__:       Cluster
* __Deployment Strategy__:   Kubernetes
* __Infrastructure__:              Own
* __Total RAM in your machine__:       5 primary nodes of 32gb each
* __Disks in use__:        SSD

## Component, Query & Data

__Affected feature__: AQL query using Arangosearch view

The count queries are returning way more results than we really have. We don't have the issue when not counting.

__Query working fine__:

```
FOR item IN observables_search_view
    SEARCH item.value == "1e100.net"
    RETURN item
```

```
Execution plan:
 Id   NodeType            Site      Est.   Comment
  1   SingletonNode       DBS          1   * ROOT
  2   EnumerateViewNode   DBS   22812860     - FOR item IN observables_search_view SEARCH (item.`value` == "1e100.net")   /* view query */
  6   RemoteNode          COOR  22812860       - REMOTE
  7   GatherNode          COOR  22812860       - GATHER   /* parallel, unsorted */
  3   ReturnNode          COOR  22812860       - RETURN item

Indexes used:
 none

Optimization rules applied:
 Id   RuleName
  1   handle-arangosearch-views
  2   scatter-in-cluster
  3   remove-unnecessary-remote-scatter
  4   parallelize-gather
```

__Count queries in error__

```
RETURN COUNT(
    FOR item IN observables_search_view
    SEARCH item.value == "1e100.net"
    RETURN item
)
```
```
Execution plan:
 Id   NodeType            Site      Est.   Comment
  1   SingletonNode       COOR         1   * ROOT
 13   SubqueryStartNode   COOR         1     - LET #1 = ( /* subquery begin */
 14   ScatterNode         COOR         1       - SCATTER
 15   RemoteNode          DBS          1       - REMOTE
  8   CalculationNode     DBS          1       - LET #5 = true   /* json expression */   /* const assignment */
  3   EnumerateViewNode   DBS   22812860       - FOR item IN observables_search_view SEARCH (item.`value` == "1e100.net")   /* view query without materialization */
 11   RemoteNode          COOR  22812860         - REMOTE
 12   GatherNode          COOR  22812860         - GATHER   /* unsorted */
 16   SubqueryEndNode     COOR         1         - RETURN  #5 ) /* subquery end */
  6   CalculationNode     COOR         1     - LET #3 = COUNT(#1)   /* simple expression */
  7   ReturnNode          COOR         1     - RETURN #3

Indexes used:
 none

Functions used:
 Name    Deterministic   Cacheable   Uses V8
 COUNT   true            true        false  

Optimization rules applied:
 Id   RuleName
  1   optimize-subqueries
  2   move-calculations-up-2
  3   handle-arangosearch-views
  4   scatter-in-cluster
  5   remove-unnecessary-remote-scatter
  6   splice-subqueries
```

```
FOR item IN observables_search_view
    SEARCH item.value == "1e100.net"
    COLLECT WITH COUNT INTO count
    RETURN count
```

```
Execution plan:
 Id   NodeType            Site      Est.   Comment
  1   SingletonNode       DBS          1   * ROOT
  2   EnumerateViewNode   DBS   22812860     - FOR item IN observables_search_view SEARCH (item.`value` == "1e100.net")   /* view query without materialization */
  9   CollectNode         DBS          1       - COLLECT  WITH COUNT INTO #2   /* count */
  7   RemoteNode          COOR         1       - REMOTE
  8   GatherNode          COOR         1       - GATHER   /* parallel, unsorted */
  3   CollectNode         COOR         1       - COLLECT AGGREGATE count = SUM(#2)   /* sorted */
  4   ReturnNode          COOR         1       - RETURN count

Indexes used:
 none

Optimization rules applied:
 Id   RuleName
  1   handle-arangosearch-views
  2   scatter-in-cluster
  3   remove-unnecessary-remote-scatter
  4   collect-in-cluster
  5   parallelize-gather
```

I tried disabling the optimization rules but it doesn't change anything. I'm under the impression that the `view query without materialization` is the one causing the issue. Maybe something is de-duplicated when the materialization is done ?

**Comment by Darkheir** [comment]
I can confirm the the `query without materialization` is what is causing the issue.

 If I force the materialization (by adding a useless filter) then it works fine:

For example:

```
FOR item IN observables_search_view
    SEARCH item.value == "1e100.net"
    FILTER item
    COLLECT WITH COUNT INTO count
    RETURN count
```

**Comment by sfialok31** [comment]
I am also seeing this on my single node instance.
It seems to be happening because of “view query without materialization” optimization.
Forcing materialization does solve this but peformance of the query becomes bad.
It seems like the view has some inconsistency i.e it has some duplicate elements.
In my case, it seemed like there were close to 80K duplicates matching a search criteria where there should only be 1 or 2 documents matching that.
So, in my case forcing materialization is making the query comparatively very slow.

Could you please take a look at this as it seems a very critical inconsistency?

Thanks in advance

**Comment by sfialok8** [comment]
Hi
Could you please take a look at this?
I am really looking forward to a fix for this.

I currently see this only happening when I update the same document multiple times in a loop (like 1000 times). And it seems to only happen when the view has primarySortOrder/storedValues defined.

Let me know if I should provide any more information to help with debugging this.

**Comment by sfialok31** [comment]
Hi
Could you please take a look at this?
I am really looking forward to a fix for this.

I currently see this only happening when I update the same document multiple times in a loop (like 1000 times). And it seems to only happen when the view has primarySortOrder/storedValues defined.

Let me know if I should provide any more information to help with debugging this.

**Comment by sfialok8** [comment]
Thank you for looking into it @gnusi 
Please do keep me posted.

**Comment by gnusi** [comment]
@sfialok31 
The issue is fixed and will be available in the upcoming `3.8.8`, `3.9.4` and `3.10.1` releases.

**Comment by sfialok31** [comment]
@gnusi 
I saw that arangodb 3.9.4 got released yesterday, but I am still seeing this issue in the newer version.
Is that expected?

**Comment by MBkkt** [comment]
@sfialok31 It maybe will be in 3.9.5, and only then 3.10.* and 3.8.*

**Comment by sfialok31** [comment]
Hi @gnusi @MBkkt 
I saw that arangodb 3.10.1 released a few days back, and I am seeing the issue in that. I saw that the arangodb's github branch 3.10.1 contains a commit that apparently fixes the bug ([commit link](https://github.com/arangodb/arangodb/commit/092bfceeda634fde633300e4ed389fbb1eb500bd)).

Could you confirm if 3.10.1 does not have the fix and this is expected?
If 3.10.1 does not have it, could you tell in which release it will be?

**Comment by MBkkt** [comment]
It was fixed in 3.9.5 which was released after 3.10.1, current state of fix for devel: https://github.com/arangodb/arangodb/pull/17562

**Comment by MBkkt** [comment]
In general I believe fix will be in 3.10.2

**Comment by sfialok31** [comment]
@MBkkt Thanks for quickly replying and confirming.

**Comment by sfialok31** [comment]
@MBkkt It still seems to be happening in 3.9.5.
Is that expected?

**Comment by MBkkt** [comment]
@sfialok31 No, can you explain what do you mean?
At least give a definition of view and query

Also if u use primary sort in definition, yes it expected :( 
Already fixed, but will be available only in 3.9.6, 3.10.2...

**Comment by MBkkt** [comment]
https://github.com/arangodb/arangodb/pull/17610 merged in 3.9

So you can try nightly from here https://download.arangodb.com/nightly/3.9/index.html probably tomorrow or day after tomorrow

**Comment by sfialok31** [comment]
@MBkkt I am referring to the same issue that this github issue is about.
When the view has primarySortOrder defined on a field, updating documents multiple times quickly leads to different document count in view and collection.
The view definition looks like this:
```
"primarySortCompression": "none",
  "writebufferActive": 0,
  "links": {
    "FilterNodes": {
      "analyzers": [
        "identity"
      ],
      "fields": {
        "city": {}
      },
      "includeAllFields": false,
      "storeValues": "none",
      "trackListPositions": false
    }
  },
  "globallyUniqueId": "h50904F6C90CD/162",
  "id": "162",
  "storedValues": [],
  "primarySort": [
    {
      "field": "name",
      "asc": true
    }
```
The documents look like this:
```
{
  "city": "delhi",
  "name": "sid"
}
```
The following queries return different results after updating the name field of this document multiple times quickly in succession:
`RETURN COUNT(FOR n IN FilterNodes FILTER n.city == "delhi" RETURN 1)` returns 1
`RETURN COUNT(FOR n IN FilterView SEARCH n.city == "delhi" RETURN 1)` returns 4

Is this issue fixed in some version? or is this fixed in the nightly builds you mentioned about?

**Comment by MBkkt** [comment]
> Is this issue fixed in some version? or is this fixed in the nightly builds you mentioned about?

@sfialok8 

Yes I wrote, views with primary sort will be fixed in 3.9.6, 3.10.2, 3.11

Now this versions not available, so you can use nightly, but you need nightly 3.9 which built after my pr. 
So you probably need to wait some days

**Comment by sfialok31** [comment]
@MBkkt So, I tested with the 3.9 nightly build. And, yeah, it looks like the issue is resolved with that commit.
Thanks.

**Comment by sfialok31** [comment]
@MBkkt Do you have an idea when 3.9.6 is expected to be released?

**Comment by MBkkt** [comment]
@sfialok8 Don't really know, maybe in middle of Decemeber (but no guarantee)

As I know should be one fix from cluster-team, but it's not ready yet
