### ISSUE TITLE
"unregistered collection used in transaction" with allowImplicit: false and traversal

### ISSUE THREAD

**Issue by Simran-B** [arangodb/arangodb#1954]
I'm seeing an error for below transaction (tested with current devel):

> unregistered collection used in transaction: users

```js
db._executeTransaction({
  collections: { 
    read: "users",
    allowImplicit: false
  },
  action: function () {
    const db = require("@arangodb").db;
    db._createStatement({ 
      query: `FOR v IN ANY "users/1234" connections RETURN v`
    }).execute().toArray().forEach(function (d) {
      /* ... */
    });
  }
});
```

If `read` is replaced by `write`, no error is thrown. This seems incorrect, since the traversal accesses another collection, `connections`. Shouldn't it require `{ read: ["users", "connections"], allowImplicit: false }` ?

No error is thrown without `allowImplicit` (or if set to true), which seems correct, as collections may be added lazily.

**Comment by hbCyber** [comment]
I'm experiencing this issue as well -- I am dealing with both read and write collections, but unless I mark them all as "write", even though I just read from some of them, this error will be thrown. I don't have any example/steps to reproduce, because my codebase is large and I don't know how much time I can afford to spend cutting down in its complexity until I reach the simplest possible reproducible case.

**Comment by Simran-B** [comment]
@jsteemann: It ignores the allowImplicit option now for reads. I can run below query without setting the actually accessed collection as to be read:

```js
db._executeTransaction({
  collections: { 
    read: "foobar" /* has to be an existing collection */
  },
  action: function () {
    const db = require("@arangodb").db;
    return db._query("FOR u IN users RETURN u._key");
  }
});
```

Write access will result in an error however, unless `write: "users"` is supplied.

According to the current docs, `allowImplicit: false` means that reads as well as writes should fail for collections that were not declared.

**Comment by jsteemann** [comment]
Should be fixed now. @Simran-B : please check

**Comment by Simran-B** [comment]
Tested at f3dfdb57d17b1ae58b670a6d43690afc73abcd23 but it still doesn't bother if read-only collections are declared or not (single instance).

Not yet covered by unit tests: `WITH` statements to declare read-only collections at the beginning of a query. Or don't these collections count as explicit?

BTW: could the error message also tell whether the collection in question is not declared for reads or writes, i.e. ArangoError: unregistered collection used in transaction **(write)**: users (while parsing) ?

**Comment by jsteemann** [comment]
@Simran-B : as far as I can see it works ok now. 

Regarding the following:

> it works without declaring users for read access if "users/1234" or DOCUMENT("users/1234") is used as start vertex for the traversal (wrong)

Using `DOCUMENT("users/1234")` should indeed produce an error if `users` was not specified for read. 
However, `"users/1234"` will only produce an error if there is an edge in `connections` that connects a document `users/1234`. If there is no such edge, the query will work. This is because `"users/1234"` is just a string from the AQL point of view. That string has the meaning "collection users plus key 1234" only in the context of the traversal. AQL will perform a lookup for an edge with that _from/_to value in `connections`. If there is such edge, it will try to read the document from the `users` collection - and fail. If there is no such edge, the query won't try to access `users` at all, and thus won't fail.

**Comment by Simran-B** [comment]
@jsteemann:

> "users/1234" will only produce an error if there is an edge in connections that connects a document users/1234. If there is no such edge, the query will work. This is because "users/1234" is just a string from the AQL point of view. 

The vertex `users/1234` does exist, but I only have to specify the edge collection `connections` for reading to make the query work. `DOCUMENT("users/1234")` does not require `users` to be declared for reading either although it should. There was no edge from that vertex to something else initially, but I see the exact same behavior after adding such an edge.

**Comment by jsteemann** [comment]
I don't think this is the case. In devel since f3dfdb57d17b1ae58b670a6d43690afc73abcd23, it will be mandatory to specify all collections used somewhere in the transaction in the transaction's collection list. If `connections` is not specified in that list, the AQL query will always fail, because it will try to read from `connections`. This is intentional, and exactly what `allowImplicit : false` should enforce. Using `users` somewhere in the query will make it mandatory to also specify `users` in the transaction's list of collections. For example, using `DOCUMENT("users/1234")` or `FOR doc IN users` will make specifying `users` mandatory. There is one exception still: using `"users/1234"` as a mere string in the query may under some circumstances not make the query fail. Precisely, in all cases in which no document lookup will be performed on the collection included in the string. This will be the case when the start vertex is `"users/1234"`, but the edge collection does not contain an edge connected to it. Then there will only be the lookup inside the `connections` collection, but no lookup in `users`.

**Comment by Simran-B** [comment]
devel@7efcc5f9611d86785e69ff48cd7ffdecdd9c6752: If I only specify `connections` for reading, there will be no error, but the result is empty:

```js
db._dropDatabase('allowImplicit');
db._createDatabase('allowImplicit');
db._useDatabase('allowImplicit');

db._create('users');
db.users.save({_key: '1234', name: 'John Smith'});
db.users.save({_key: 'heinz', name: 'Heinz'});

db._createEdgeCollection('connections');
db.connections.save({_from: 'users/1234', _to: 'users/heinz'});
db.connections.save({_from: 'users/heinz', _to: 'users/missing'});

var query = `
  FOR u IN ['1234', 'heinz']
    FOR v IN ANY DOCUMENT('users', u) connections
      RETURN v
`;

print('\n0. AQL query without transaction');
print('   RESULT length: ' + db._createStatement({query, count: true}).execute().count());

[[], ['users'], ['connections'], ['users', 'connections']].forEach( function(colls, i) {
  try {
    print(`\n${i+1}. Collections (read): ${colls.length ? colls.join(', ') : ' - '}`);
    let result = db._executeTransaction({
      collections: {
        read: colls,
        allowImplicit: false
      },
      action: function () {
        const db = require('@arangodb').db;
        return db._createStatement({
          query: `FOR u IN ['1234', 'heinz']
                    FOR v IN ANY DOCUMENT('users', u) connections
                      RETURN v`,
          count: true
        }).execute().toArray()
      }
    });
    print('   RESULT length: ' + result.length);
  } catch(e) {
    print('   ERROR: ' + e.message);
  }
});
```

```
0. AQL query without transaction
   RESULT length: 3

1. Collections (read):  -
   ERROR: unregistered collection used in transaction: connections (while parsing)

2. Collections (read): users
   ERROR: unregistered collection used in transaction: connections (while parsing)

3. Collections (read): connections
   RESULT length: 0

4. Collections (read): users, connections
   RESULT length: 3
```

**Comment by jsteemann** [comment]
Result here is:
```
0. AQL query without transaction
   RESULT length: 3

1. Collections (read):  - 
   ERROR: unregistered collection used in transaction: connections [read] (while parsing)

2. Collections (read): users
   ERROR: unregistered collection used in transaction: connections [read] (while parsing)

3. Collections (read): connections
   ERROR: unregistered collection used in transaction: users [read] (while executing)

4. Collections (read): users, connections
   RESULT length: 3
```

**Comment by Simran-B** [comment]
The build script on the test server was broken, it did not start the correct executable. Everything okay now!

**Comment by jsteemann** [comment]
Thanks for confirmation!

**Comment by hbCyber** [comment]
Is there any chance you can test your bugfix with my issue? Seems related
https://github.com/arangodb/arangodb/issues/1967
