### ISSUE TITLE
supervisor dies instead of respawning child

### ISSUE THREAD

**Issue by leroux** [arangodb/arangodb#2140]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.0

On this operating system:
- [x] Linux Ubuntu .deb

## my problem is

supervisor dies after a child is sent a SIGSEGV.

The issue can be reproduced by running the following:

Following [Documentation: Supervisor](https://github.com/arangodb/arangodb/blob/c316505547993df038f75686ac9a22ef3a5d847b/Documentation/Books/Manual/Administration/Configuration/GeneralArangod.mdpp#L52-L85).

```
root@ubuntu1404:~# uname -a
Linux ubuntu1404 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

root@ubuntu1404:~# wget -q https://www.arangodb.com/repositories/arangodb3/xUbuntu_14.04/amd64/arangodb3_3.0.10_amd64.deb

root@ubuntu1404:~# sha256sum arangodb3_3.0.10_amd64.deb
d107583f4e0768ffec760c2915143ae1e101de6139ec43e75a0dc6b3644019c3  arangodb3_3.0.10_amd64.deb

root@ubuntu1404:~# dpkg -i arangodb3_3.0.10_amd64.deb >/dev/null

root@ubuntu1404:~# service arangodb3 status
 * arangod is running

root@ubuntu1404:~# ps fax | grep arango | grep -v grep
 2598 ?        Ss     0:00 /usr/sbin/arangod --uid arangodb --gid arangodb --pid-file /var/run/arangodb/arangod.pid --temp.path /var/tmp/arangod --log.foreground-tty false --supervisor
 2599 ?        Sl     0:01  \_ /usr/sbin/arangod --uid arangodb --gid arangodb --pid-file /var/run/arangodb/arangod.pid --temp.path /var/tmp/arangod --log.foreground-tty false --supervisor

root@ubuntu1404:~# kill -SIGSEGV 2599

root@ubuntu1404:~# ps fax | grep arango | grep -v grep

root@ubuntu1404:~# echo $?
1
```

**Comment by leroux** [comment]
Here is the syscall trace.

```
> ps fax | grep arango | grep -v grep                                                                                                                                                                                                                                                                                                                                                              

 3653 ?        Ss     0:00 /usr/sbin/arangod --uid arangodb --gid arangodb --pid-file /var/run/arangodb/arangod.pid --temp.path /var/tmp/arangod --log.foreground-tty false --supervisor
 3654 ?        Sl     0:01  \_ /usr/sbin/arangod --uid arangodb --gid arangodb --pid-file /var/run/arangodb/arangod.pid --temp.path /var/tmp/arangod --log.foreground-tty false --supervisor

> kill -SIGSEGV 3654 # kill child process
```

strace parent (supervisor?) process:
```
> strace -p 3653
Process 3653 attached
wait4(3654, [{WIFSIGNALED(s) && WTERMSIG(s) == SIGSEGV}], 0, NULL) = 3654
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_KILLED, si_pid=3654, si_status=SIGSEGV, si_utime=140, si_stime=29} ---
close(3)                                = 0
exit_group(0)                           = ?
+++ exited with 0 +++
```

strace child process:
```
> strace -p 3654 2>&1 | grep -v nanosleep
Process 3654 attached
restart_syscall(<... resuming interrupted call ...>) = 0
+++ killed by SIGSEGV +++
```

**Comment by arges** [comment]
I think this is related to the sysvinit script. For comparison in Ubuntu 16.04.

With systemd:

```
root@test1:~# service arangodb3 status
● arangodb3.service - LSB: arangodb
   Loaded: loaded (/etc/init.d/arangodb3; bad; vendor preset: enabled)
   Active: active (running) since Wed 2016-11-02 12:56:48 UTC; 8s ago
     Docs: man:systemd-sysv-generator(8)
   CGroup: /system.slice/arangodb3.service
           ├─3528 /usr/sbin/arangod --uid arangodb --gid arangodb --pid-file /var/run/arangodb/arangod.pid --tem
           └─3529 /usr/sbin/arangod --uid arangodb --gid arangodb --pid-file /var/run/arangodb/arangod.pid --tem

Nov 02 12:56:46 test1 systemd[1]: Starting LSB: arangodb...
Nov 02 12:56:46 test1 arangodb3[3483]:  * Starting arango database server arangod
Nov 02 12:56:48 test1 arangodb3[3483]: {startup} starting up in daemon mode
Nov 02 12:56:48 test1 arangodb3[3483]:    ...done.
Nov 02 12:56:48 test1 systemd[1]: Started LSB: arangodb.
Nov 02 12:56:48 test1 arangodb3[3483]: changed working directory for child process to '/var/tmp'
root@test1:~# ps fax | grep arango | grep -v grep
 3528 ?        Ss     0:00 /usr/sbin/arangod --uid arangodb --gid arangodb --pid-file /var/run/arangodb/arangod.pid --temp.path /var/tmp/arangod --log.foreground-tty false --supervisor
 3529 ?        Sl     0:01  \_ /usr/sbin/arangod --uid arangodb --gid arangodb --pid-file /var/run/arangodb/arangod.pid --temp.path /var/tmp/arangod --log.foreground-tty false --supervisor
root@test1:~# kill -SIGSEGV 3529
root@test1:~# ps fax | grep arango | grep -v grep
 3528 ?        Ss     0:00 /usr/sbin/arangod --uid arangodb --gid arangodb --pid-file /var/run/arangodb/arangod.pid --temp.path /var/tmp/arangod --log.foreground-tty false --supervisor
 3529 ?        Dl     0:01  \_ /usr/sbin/arangod --uid arangodb --gid arangodb --pid-file /var/run/arangodb/arangod.pid --temp.path /var/tmp/arangod --log.foreground-tty false --supervisor
```

With sysvinit:

```
root@test1:~# service arangodb3 status
 * arangod is running
root@test1:~# ps fax | grep arango | grep -v grep
 2326 ?        Ss     0:00 /usr/sbin/arangod --uid arangodb --gid arangodb --pid-file /var/run/arangodb/arangod.pid --temp.path /var/tmp/arangod --log.foreground-tty false --supervisor
 2327 ?        Sl     0:01  \_ /usr/sbin/arangod --uid arangodb --gid arangodb --pid-file /var/run/arangodb/arangod.pid --temp.path /var/tmp/arangod --log.foreground-tty false --supervisor
root@test1:~# kill -SIGSEGV 2327
root@test1:~# ps fax | grep arango | grep -v grep
```

**Comment by tsh56** [comment]
The logic in SupervisorFeature.cpp appears to have the supervisor gracefully exit on non graceful shutdown of the child process. I believe the `if (!DONE)` conditional should be reversed.

`142       DONE = false;
143
144       int status;
145       int res = waitpid(_clientPid, &status, 0);
146       bool horrible = true;
147
148       if (!DONE) {
149         done = true;
150         horrible = false;
151       }
152       else {
153         ... logic to examine cause of death
`

Once this logic is corrected the supervisor at least tries to restart the process but that fails during restart. LoggerFeature::prepare is called again on restart, but this isn't allowed because it calls Logger::setUseLocalTime which can't be called while the logger is active. You can setup logic to only call prepare on the first startup, but this still causes a problem for the child on restart. When the supervisor starts a child process for the second time the forked process inherits an already initialized Logger feature, which causes the process to exit.

**Comment by jsteemann** [comment]
Correct, I was investigating the issue in parallel and found the same reason.
I am currently working on a fix for this.
Thanks for debugging the issue that far!

**Comment by leroux** [comment]
@jsteemann, confirmed your fix (ae836cfa3fbd) on v3.0.8. Checked out v3.0.8 and applied your patch.

**Comment by jsteemann** [comment]
Fix has been pushed into 3.0, 3.1 and devel branches. Will be included in releases 3.0.11, 3.1.0.

**Comment by tsh56** [comment]
When is 3.0.11 expected to release?

**Comment by leroux** [comment]
@jsteemann I see there was a 3.1 release with this fix, but still not 3.0.11. Is there a plan to test/publish that sometime soon?

**Comment by jsteemann** [comment]
@leroux @tsh56: the fix is also included in the 3.0 branch, so it will be part of the next 3.0 release (3.0.11).
We haven't started a new 3.0 release build yet, but also from my point of view it's time to do it soon. 
The last 3.0 release was about 5-6 weeks ago, and we have accumulated enough bug fixes for a new release IMHO. So I expect it to be released soon.

**Comment by jwinters7** [comment]
Any update on when 3.0.11 will be available?

**Comment by dothebart** [comment]
We're currently triggering the 3.0.12 build since there are already more fixes since we did the .11 tag. It should be available tomorow.

**Comment by dothebart** [comment]
3.0.12 is available for download via the regular upgrade channels - closing.
