### ISSUE TITLE
Updating doc w/ fields of non-representable types in web UI replaces them with the string "non-representable type"

### ISSUE THREAD

**Issue by miguel-porto** [arangodb/arangodb#2288]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [x] 3.0
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [x] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [ ] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

The issue can be reproduced using this dataset:

Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [ ] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database?

Hmm, the title is self-explicit and I know you are aware of this, but just to remind that it's inconvenient because the unaware will inadvertently lose data when using the "save" document in the web UI.
Maybe base64 encode all the non-representable types to avoid data loss on save? Or maybe just display a warning to the user that he's about to save something where data will be lost?

Cheers!
Miguel

**Comment by jsteemann** [comment]
Yes, saving should indeed not lead to loss.
However, I am wondering how you got the non-representable types into the documents in the first place.
What mechanism to you use to store the documents (i.e. which driver)?

**Comment by miguel-porto** [comment]
Well, they were just java Date objects with the Java driver... I know I could [override](https://github.com/arangodb/arangodb-java-driver/issues/71) the serializer, but IMHO the web UI should know how to workaround such cases, or better, the server itself...

**Comment by mpv1989** [comment]
We are currently changing the serialization of java.date in the driver so that it is stored as String instead of vpack.date. The problem is that vpack.date is not supported from ArangoDB, Shell or webUI.
A new version should be released within the next days.

Best
Mark

**Comment by miguel-porto** [comment]
Hmm, that solves this particular problem, but my concern goes beyond it; what about storing binary objects in general? Shouldn't ArangoDB support binary objects throughout, now that it is VPack-based, just by e.g. base64/base91 encoding them?
(I'm not talking about BLOBs, if size is a problem, supporting small BOBs would be already an excellent feature!)
Regards
Miguel

**Comment by mpv1989** [comment]
I implemented serialization from java `byte[]` to base64 coded vpack.string and reversed for just a few hours. You can already test it with version `4.1.8-SNAPSHOT`. I will release a new version within this week.

**Comment by miguel-porto** [comment]
This is very good. I think this feature will be very handy, specially if you want to have some JNI native code outputting binary data (as I will need later!)
Still have a doubt. Let me see if I understand correctly. With VPack you can store any Java object of any class in the DB, even if there is no serializer. The trouble is only that the other interfaces (arangodump/restore, the shell, the WebUI...) cannot handle binary data, so you have to really store in the DB the ASCii encoded version to enable compatibility. For example, you cannot use arangodump to export a DB with binary data, right?
However, I'm still in doubt regarding the scope of this issue: I think it should be the ArangoDB server itself that should handle these conversions binary-text. Storing base64 encoded data in the DB is not ideal. Binary data should be treated as binary all throughout, and only ASCii encoded when it is really needed (i.e. when exporting to JSON). Pardon if I'm not getting it.

Thanks for this feature!
Miguel

**Comment by mpv1989** [comment]
Hi Miguel,

Starting with ArangoDB 3.0 we moved our internal storage to the VelocyPack format, which provides support for all JSON datatypes plus some commonly datatypes not available in JSON. That means ArangoDB's internal storage is capable of storing non-JSON data now, but all of ArangoDB's APIs remained unchanged for backwards-compatibility.  Specifically, the existing JSON APIs are all JSON-based, so they don't provide any meaningful way for converting non-JSON data into JSON. Extending the JSON format with non-portable annotations was not an option for us because this wouldn't be supported by client drivers.
With ArangoDB 3.1 we added the VelocyStream, protocol which allows sending raw VelocyPack values over the wire. So there is now a way for shipping non-JSON values from an application to ArangoDB. But still sending non-JSON data to ArangoDB will cause follow up issues, for example, with the web interface. The web interface is running in the browser and will use the JSON-based HTTP API. And there we have the problem again that there is no sensible way of expressing non-JSON datatypes in JSON. Any custom extensions/annotations for JSON will not work here as they are not portable. All other JSON-based APIs will have the same problem: they simply cannot return meaningful data for non-JSON values. 
The proper solution for this is to make the web interface and all client tools use VelocyPack as well. This would allow using all datatypes (including non-JSON types) and prevents conversion losses. Additionally on the server level some works needs to be done to make some operations aware of non-JSON types. 
Overall that is a lot of work, and we haven't yet found the time to do it. But it's definitely something we want to do in a future release.

Best
Mark

**Comment by miguel-porto** [comment]
Hi Mark,
Thank you for the detailed explanation. I see the problem. So, for now, the solution is that it's up to the user to implement custom serializers to handle non-conventional data types, if he wants compatibility with the shell and the dump/restore. Not a problem!
Thanks!
I guess we can close this.
Best!
Miguel
