### ISSUE TITLE
Error response to basic query in clustered environment

### ISSUE THREAD

**Issue by ldap4life** [arangodb/arangodb#3093]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.2

Mode:
- [x] Cluster

Storage-Engine:
- [x] mmfiles

On this operating system:
  - [x] own infrastructure
- [x] Linux 
  - [x] Fedora .rpm

These are the steps to reproduce:
Apologies, this has happened 4 times over a period of a couple of days. It happens when running a basic aql query on a small sized collection. The cluster has 5 agents, 2 coordinators, and 2 dbs. The query looks similar to "FOR l in collection filter l.date < 123 and l.date > 121 sort l.date limit 10 return l" I have not been able to reproduce the issue. 

The following problem occurs: 
Instead I would be expecting: No error.

com.arangodb.ArangoDBException: Response: 500, Error: 4 - Error message received from shard 's1010223' on cluster node 'PRMR-8bce2170-26f5-4c77-ac72-4d2c25944a54':  (exception location: /var/lib/jenkins/workspace/RELEASE__BuildPackages/arangod/Aql/ClusterBlocks.cpp:1215). Please report this error to arangodb.com (while executing) (exception location: /var/lib/jenkins/workspace/RELEASE__BuildPackages/arangod/RestHandler/RestCursorHandler.cpp:130). Please report this error to arangodb.com

I suspect this could be a networking issue in our environment, but was compelled to make this issue by the message in the error. Thank you.

**Comment by dothebart** [comment]
Hi, 
meanwhile Arangodb 3.2.8 has been released with many bugfixes to the cluster and memory management. 
Can you please upgrade and retry and check back whether this issue still persists?

**Comment by dothebart** [comment]
Closing as solved with 3.2.8

**Comment by ldap4life** [comment]
Hi apologies for the late reply,  I have upgraded to the latest 3.3 and can confirm this issue still happens.

com.arangodb.ArangoDBException: Response: 500, Error: 4 - AQL: Error message received from shard '' on cluster node 'PRMR-a5c5f3db-8a7b-493b-b74d-4baeb0302b7c':  (exception location: /var/lib/otherjenkins/workspace/RELEASE__BuildPackages/arangod/Aql/ClusterBlocks.cpp:1250). Please report this error to arangodb.com (while executing) (exception location: /var/lib/otherjenkins/workspace/RELEASE__BuildPackages/arangod/RestHandler/RestCursorHandler.cpp:134). Please report this error to arangodb.com
	at com.arangodb.internal.http.HttpCommunication.checkError(HttpCommunication.java:418)
	at com.arangodb.internal.http.HttpCommunication.execute(HttpCommunication.java:273)
	at com.arangodb.internal.http.HttpCommunication.execute(HttpCommunication.java:241)
	at com.arangodb.internal.http.HttpProtocol.execute(HttpProtocol.java:48)
	at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:58)
	at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:47)
	at com.arangodb.ArangoDatabase.query(ArangoDatabase.java:343)

The error is slightly different now. There is a different line number, and maybe significant: the shard name is not shown anymore.
