### ISSUE TITLE
Performance Issues with replication/logger-follow

### ISSUE THREAD

**Issue by darkfrog26** [arangodb/arangodb#3291]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- 3.2

Mode:
- Single-Server

Storage-Engine:
- rocksdb

On this operating system:
- Linux 
  - Ubuntu .deb

I've written something similar to arangochair to utilize the `replication/logger-follow` end-point to poll for database changes (https://github.com/outr/scarango/blob/master/driver/src/main/scala/com/outr/arango/ArangoReplication.scala#L61-L98). This works very well, but I'm noticing that ArangoDB's CPU utilization is pretty high (around 30% consistently) and the HD is very active if I'm checking `replication/logger-follow` every 500 milliseconds.  I presumed that this end-point would be a primarily "in-memory" operation but that seems not to be the case.

**Comment by jsteemann** [comment]
With the MMFiles engine this should be a mostly in-memory operation, provided the requests WAL file ranges are from one of the last few WAL logfiles.
With the RocksDB engine this call seems to physically open the WAL logfiles using `fopen` and read from them using `fread` etc. This may cause file I/O.

**Comment by darkfrog26** [comment]
Shouldn't the most recent log entries be held in memory to avoid performance issues resulting from this?

**Comment by dothebart** [comment]
It seems that rocksdb isn't acting smart here as @jsteemann put it. We're currently simply using this rocksdb implementation. But yes, this needs to be improved.

**Comment by darkfrog26** [comment]
In MongoDB they support open cursors so you can continually receive updates as new results to the query arrive (which, if written properly, can receive all changes to a collection as they occur).  This would be a far superior solution if ArangoDB supported it.

**Comment by graetzer** [comment]
RocksDB does not seem to cache WAL files, we will investigate this further

**Comment by darkfrog26** [comment]
Hoping I see this in 3.2.4. ;)

**Comment by graetzer** [comment]
@darkfrog26  Do you mean https://docs.mongodb.com/manual/core/tailable-cursors/

**Comment by darkfrog26** [comment]
@graetzer yes, but for the moment I would just be happy with being able to hit `logger-follow` without it consuming a lot of CPU and HD resources.

**Comment by dothebart** [comment]
We usually add the 'fixed' label once a change has been implemented. Once its been merged for the next maintenance release the target milestone is adjusted. Once that is released, we close the issue with the notice that the fix is available. So you will get the feedback on which timeframe this is implemented and released.

**Comment by darkfrog26** [comment]
Is any work being done on this?  I know you guys have a ton of issues on your plate, but this is a pretty big deal for one of my clients and if it isn't resolved soon the client may require me to switch to MongoDB for their project.

**Comment by graetzer** [comment]
I would expect to be able to look at this on Friday.

**Comment by darkfrog26** [comment]
@graetzer wonderful, thank you!

**Comment by matthewvon** [comment]
Greetings @darkfrog26.  I am actively working this issue and another issue that is loosely related.  It would help if you could share two data items:  how many logical CPU cores in your test environment and roughly the level of write load (x records per second, averaging y bytes each).  The loosely related issue relates to when rocksdb's compactions levels are high and swamp the available CPU time ... hence my question.

**Comment by darkfrog26** [comment]
My staging server I'm running this on is as follows:
Dual Xeon L5630 - 8 Cores (16 HT Cores)

The IO hit isn't substantial, but it's constant.  When I test locally, and am polling the database every 250ms, I'm seeing constant HD light-ups.  It's bothersome in a low-load situation and concerning for high loads.

**Comment by matthewvon** [comment]
Thank you.  I forgot to ask what operating system (Linux, Windows, Mac, etc)?

**Comment by darkfrog26** [comment]
Ubuntu, although this should be applicable to all versions I would expect.

**Comment by matthewvon** [comment]
Here is my assessment:  the rocksdb code opens each archived WAL file at least once, then reads the content from each file at least once (maybe more if the same file has content applicable in multiple calls).  Yes, this is going to cause the drive light to blink.  rocksdb makes no attempt to hint to the operating system that the WAL file could be opened and read multiple times.  Such hinting is possible.  

I am proceeding with testing a virtual override to the NewWritableFile() function that will use the existing function to perform the actual file creation, but will afterward establish the hinting to the operating system to keep the file's contents in the system file cache where possible.

I have previously used this technique for performance gains on Basho's leveldb.  It has a good chance of working the same magic here.  However, I am running a marathon on Saturday and will likely be power napping the entire weekend.  I expect it will be Monday or Tuesday before I report again.

**Comment by darkfrog26** [comment]
@matthewvon thanks for the update. No worries, as long as progress is being made I can keep the client appeased.

**Comment by matthewvon** [comment]
Status:  this has been "next task" on my list for two weeks.  But other things have continued to interrupt.  I have not forgotten the work, just not executed.

**Comment by darkfrog26** [comment]
@matthewvon thanks for the update.  This is a problem I'm going to need to deal with in the near future.

**Comment by matthewvon** [comment]
I have duplicated the bug.  I have hacked proposed modifications into RocksDB, and bug goes away.  So we know the solution.  I am happy to share the hack if you desire this immediately.

We are interested in this fix long term.  My next steps are to create a patch that is external to RocksDB.  This will be an alternate rocksdb::Env object that contains the changes leading to this fix.

While that should be one day's work ... going to guess it will take a week to perform that day's work.  Life at ArangoDB is really hopping right now.

**Comment by darkfrog26** [comment]
@matthewvon no worries...I'll wait for it to make its way into the official release.  Any change this can make it in for 3.3?

**Comment by matthewvon** [comment]
Notes:  current RocksDB release within ArangoDB is 5.6.2.  Half of this bug was fixed and released in RocksDB 5.7.1: https://github.com/facebook/rocksdb/pull/2573

**Comment by matthewvon** [comment]
Retest suggests that PR is all that is needed.  Removing the Fadvise call in PosixSequentialFile::Read() is sufficient.  There is no need to also apply an Fadvise WILLNEED call on the log file's creation.

**Comment by jsteemann** [comment]
@matthewvon : your patch that removes the fadvise call in RocksDB has been merged into our version of RocksDB. The fix is included in ArangoDB release 3.2.6.

**Comment by jsteemann** [comment]
Can one of you recheck with the 3.2.6 release and check if this fixes the problem? Thanks.

**Comment by darkfrog26** [comment]
Just updated to 3.2.6 on dev and this does appear to be fixed.  I'm not seeing the crazy hard drive light activity I was seeing before, but I'll continue to keep an eye on it.

**Comment by darkfrog26** [comment]
Thanks guys for your hard work on this, it's greatly appreciated.

**Comment by dothebart** [comment]
Ok, great! Closing.
