### ISSUE TITLE
Request timeout reached - arangodump

### ISSUE THREAD

**Issue by Calrain** [arangodb/arangodb#3857]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [x] 3.2.8
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [x] Single-Server

Storage-Engine:
- [ ] mmfiles
- [x] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [x] Windows, version: Windows Server 2016
- [ ] MacOS, version:

When running ArangoDB on a Windows Server 2016, I'm getting a `[2812] ERROR got invalid response from server: Request timeout reached` when trying to dump data with the `arangodump` tool.

The server is running SSL with a self signed certificate created with openssl, and running on port 8530. It is possible to connect to the server via `https://localhost:8530`

Example command line:

    C:\arangodb\bin\usr\bin\arangodump --server.endpoint ssl://localhost:8530 --server.username root --server.database my_database --output-directory "C:\my_backup_directory" --overwrite true --include-system-collections true

This is run in a Command Prompt running as Administrator.

Output of above command line:

    C:\arangodb\bin\usr\bin\arangodump --server.endpoint ssl://localhost:8530 --server.username root --server.database my_database --output-directory "C:\my_backup_directory" --overwrite true --include-system-collections true  
    Please specify a password:  
    Server version: 3.2.8  
    Connected to ArangoDB 'ssl://localhost:8530', database: 'my_database', username: 'root'  
    Writing dump to output directory 'C:\my_backup_directory'  
    [31m2017-12-01T06:16:01Z [4996] ERROR got invalid response from server: Request timeout reached  
    [0mProcessed 0 collection(s), wrote 0 byte(s) into datafiles, sent 0 batch(es)

Note: there are odd characters at the start of the last two output lines, not sure why.

Also to confirm, root has 'Administer' access to the database in question and can access the database via the web UI

I would like to backup a database to load it into another database on another server, not sure how to progress with arangodump.

Thanks

**Comment by Simran-B** [comment]
Hi @Calrain,

About the odd characters, see #3741 (we are working on a fix).

Regarding the timeout, I'm not sure if `--server.request-timeout <number>` would help, as this seems to be about the **client** timeout period being too short, not the server's.

@jsteemann Do we need `--request-timeout` and `--connect-timeout` like in #94 for arangodump and possibly some other tools as well?

**Comment by Calrain** [comment]
@Simran-B Sadly `--server.request-timeout <number>` doesn't resolve the issue.

The error messages comes back instantly, it's not waiting for a period of time and then timing out.

I added `--server.timeout 6000` but it just fails right away.

**Comment by Calrain** [comment]
Quick update, have also tested on a 3.2.8 server running on Windows 2016 with mmfiles and the result is the same, unable to arangodump.

**Comment by dothebart** [comment]
@Calrain can you use arangodump to that windows host from a linux machine? did you try specifying `127.0.0.1` instead of `localhost` ? 
On linux even only having a listening `netcat` with me not replying will respect the timeout.

**Comment by Calrain** [comment]
Apologies for the late response, but I'm now back in this space again.

I've tried the FQDN of the server, the short DNS name, localhost, 127.0.01, and ::1, but none are working.

Will upgrade to latest 3.2 branch and keep testing.

**Comment by Calrain** [comment]
Note: this error happens on ArangoDB 3.2.9 as well (originally was testing on ArangoDB 3.2.28)

**Comment by Calrain** [comment]
I've now upgraded a test environment to ArangoDB 3.3.1 and the error is still happening.

When testing the arangodump facility with SSL enabled in arangod, do you also test with self-signed certificates?

The OpenSSL template format that I use is (with redactions where appropriate):

```
[req]
default_bits = 2048
prompt = no
default_md = sha256
req_extensions = req_ext
distinguished_name = dn
 
[ dn ]
C=AA
ST=BBB
L=CCC
O=DDD
OU=EEE
emailAddress=FFF@GGG.com
CN = myserver@GGG.com

[ req_ext ]
subjectAltName = @alt_names
 
[ alt_names ]
DNS.1 = myserver@GGG.com
DNS.2 = myserver
```

The only reason I'm attaching this is in-case there is another SSL setting that ArangoDB expects to see and I'm not setting.

**Comment by dothebart** [comment]
Hi, 
to have a more interactive testing, do you see arangosh working for your system? (its using the same http client facility with the same openssl interfacing)
Can you execute queries, or run a `db.collection.toArray()` with one of your collections?

**Comment by Calrain** [comment]
Thanks for getting back.

Yes, I'm able to successfully connect with arangosh using the command:
`arangosh --server.endpoint ssl://myserver:8530` 

I can then select a database and perform .toArray() on a collection.

The odd thing is that all external connectivity works fine with arangod bound to ssl.

To get around it temporarily I've had to do both a SSL binding to the external IP address and a TCP binding to localhost port 8529, to at least block connections to ArangoDB from external processes to the server.

**Comment by vinaypyati** [comment]
Hi @Calrain, 

There have been significant changes/bug fixes to 3.3.x series and also we have now released 3.4.0 RC1. You can find it [here ](https://www.arangodb.com/download-technical-preview/). Please try reproducing the issue and let us know your feedback. 

Thanks!

**Comment by maxkernbach** [comment]
Hi @Calrain,

did you already try 3.4 RC1?
FYI: The latest available 3.4 Release Candidate is RC2 and can be found in the [download section](https://www.arangodb.com/download-technical-preview/).

Your feedback is highly appreciated!

**Comment by jsteemann** [comment]
I don't have any idea why this has happened (or still happens), as it seems the timeout response comes back instantly after connecting.
As it seems to have worked with non-SSL connections, this issue is likely due to some problems in the underlying SSL implementation or the SSL integration part in ArangoDB. 
Several changes related to SSL internal handling have been done in the ArangoDB 3.3 and 3.4 series since this issue was opened, including an SSL library upgrade.

However, it is unclear whether current 3.3 or 3.4 (currently in release candidate stage) will fix this issue, but I think it is worth a try.
@Calrain : is it possible you upgrade to latest 3.3 or try 3.4 RC to see if that fixes the issue? Thanks!
