### ISSUE TITLE
VERSION file keeps disappearing

### ISSUE THREAD

**Issue by ile** [arangodb/arangodb#4272]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.3

Mode:
- [x] Single-Server

Storage-Engine:
- [x] mmfiles

On this operating system:
- [x] Linux 
  - [x] Ubuntu .deb

These are the steps to reproduce:
1) Crash your computer (Ubuntu 16, bare metal).

VERSION file keeps disappearing. It disappears almost every time when the computer crashes. This has happened as long as I can remember, with every Arangodb version.

```
2018-01-10T19:00:54Z [2458] INFO detected operating system: Linux version 4.4.0-108-generic (buildd@lgw01-amd64-003) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5) ) #131-Ubuntu SMP Sun Jan 7 14:34:49 UTC 2018
2018-01-10T19:00:54Z [2458] WARNING {memory} maximum number of memory mappings per process is 65530, which seems too low. it is recommended to set it to at least 128000
2018-01-10T19:00:54Z [2458] WARNING {memory} execute 'sudo sysctl -w "vm.max_map_count=128000"'
2018-01-10T19:00:54Z [2458] WARNING {memory} /sys/kernel/mm/transparent_hugepage/enabled is set to 'always'. It is recommended to set it to a value of 'never' or 'madvise'
2018-01-10T19:00:54Z [2458] WARNING {memory} /sys/kernel/mm/transparent_hugepage/defrag is set to 'always'. It is recommended to set it to a value of 'never' or 'madvise'
2018-01-10T19:00:54Z [2458] WARNING {memory} execute 'sudo bash -c "echo madvise > /sys/kernel/mm/transparent_hugepage/enabled"'
2018-01-10T19:00:54Z [2458] WARNING {memory} execute 'sudo bash -c "echo madvise > /sys/kernel/mm/transparent_hugepage/defrag"'
2018-01-10T19:00:54Z [2458] INFO using storage engine mmfiles
2018-01-10T19:00:54Z [2458] INFO {syscall} file-descriptors (nofiles) hard limit is 131072, soft limit is 131072
2018-01-10T19:00:54Z [2458] INFO {authentication} Authentication is turned on (system only), authentication for unix sockets is turned on
2018-01-10T19:00:56Z [2458] FATAL Database version check failed for 'somecomp1'. Please inspect the logs for any errors
```

```
# arangosh --version
3.3.1

architecture: 64bit
arm: false
asan: false
asm-crc32: true
assertions: false
boost-version: 1.62.0
build-date: 2017-12-28 20:30:23
build-repository: tags/v3.3.1-0-g1c01d07
compiler: gcc [5.4.0]
cplusplus: 201103
debug: false
endianness: little
failure-tests: false
fd-client-event-handler: poll
fd-setsize: 1024
full-version-string: ArangoDB 3.3.1 [linux] 64bit, using jemalloc, VPack 0.1.30, RocksDB 5.6.0, ICU 58.1, V8 5.7.492.77, OpenSSL 1.0.2g  1 Mar 2016
icu-version: 58.1
jemalloc: true
maintainer-mode: false
openssl-version: OpenSSL 1.0.2g  1 Mar 2016
platform: linux
reactor-type: epoll
rocksdb-version: 5.6.0
server-version: 3.3.1
sizeof int: 4
sizeof void*: 8
sse42: false
unaligned-access: true
v8-version: 5.7.492.77
vpack-version: 0.1.30
zlib-version: 1.2.11
```

**Comment by jsteemann** [comment]
Potential fix, which will force a sync of the file stream with the underlying storage:
```
diff --git a/lib/V8/v8-utils.cpp b/lib/V8/v8-utils.cpp
index 86efa039ea..33e9e9e2ae 100644
--- a/lib/V8/v8-utils.cpp
+++ b/lib/V8/v8-utils.cpp
@@ -2681,7 +2681,7 @@ static void JS_Write(v8::FunctionCallbackInfo<v8::Value> const& args) {
                                      "invalid <content> buffer value");
     }
 
-    std::ofstream file;
+    std::fstream file;
 
     file.open(*name, std::ios::out | std::ios::binary);
 
@@ -2689,6 +2689,7 @@ static void JS_Write(v8::FunctionCallbackInfo<v8::Value> const& args) {
       file.write(data, size);
       if (flush) {
         file.flush();
+        file.sync();
       }
       file.close();
       TRI_V8_RETURN_TRUE();
@@ -2700,7 +2701,7 @@ static void JS_Write(v8::FunctionCallbackInfo<v8::Value> const& args) {
       TRI_V8_THROW_TYPE_ERROR("<content> must be a string");
     }
 
-    std::ofstream file;
+    std::fstream file;
 
     file.open(*name, std::ios::out | std::ios::binary);
 
@@ -2708,6 +2709,7 @@ static void JS_Write(v8::FunctionCallbackInfo<v8::Value> const& args) {
       file << *content;
       if (flush) {
         file.flush();
+        file.sync();
       }
       file.close();
       TRI_V8_RETURN_TRUE();
```
If the above helps is speculation right now.
What type of filesystem is in use for the ArangoDB database directory, and/or which mount options are used for it? 
Additionally, I interpret "bare metal" as that the arangod process and the Ubuntu OS themselves do not run in any virtualization environment nor containers. Is that correct?

**Comment by ile** [comment]
Yes, bare metal meant that no virtualization isn't used. Didn't want to use the negation expression, but "bare metal" isn't that clear either.

The file system is:
```
/dev/sda1      ext4      103G   68G   30G  70% /
```

**Comment by jsteemann** [comment]
Can you also show the mount options for that filesystem? Thanks!

**Comment by ile** [comment]
You mean:
```
/dev/sda1 on / type ext4 (rw,relatime,errors=remount-ro,data=ordered)
```

**Comment by jsteemann** [comment]
Yes, thanks. That seem to be the default ext4 mount options on Ubuntu.

**Comment by ile** [comment]
Ok. If you need any more help, it's quite easy to reproduce here. I'll just shut down the computer from the main switch/unplug it. Then, when restarting, the VERSION file is usually nowhere to be seen. 

This applies to the database that was in active use with arangojs JavaScript module, and connected into with Node.js.

**Comment by jsteemann** [comment]
A potential fix for this is in this PR:
https://github.com/arangodb/arangodb/pull/4311

I say "potential" because this is just me guessing that for some reason the file contents are only present in kernel buffers and not flushed to disk when the server crashes. But that's pure speculation.
In case the VERSION file disappears again (before the potential fix has been released), it can be replaced with something like the following:

**3.2**:
```
{"version":30210,"tasks":{"setupGraphs":true,"setupUsers":true,"createUsersIndex":true,"createModules":true,"createRouting":true,"insertRedirectionsAll":true,"setupAqlFunctions":true,"createStatistics":true,"createFrontend":true,"setupQueues":true,"setupJobs":true,"createJobsIndex":true,"updateUserModels":true}}
```

**3.3**:
```
{"version":30302,"tasks":{"setupGraphs":true,"setupUsers":true,"createUsersIndex":true,"createModules":true,"createRouting":true,"insertRedirectionsAll":true,"setupAqlFunctions":true,"createStatistics":true,"createFrontend":true,"setupQueues":true,"setupJobs":true,"createJobsIndex":true,"setupApps":true,"createAppsIndex":true,"setupAppBundles":true,"updateUserModels":true}}
```

**Comment by ile** [comment]
Ok, thanks.

(I don't normally use root account directly, but when I do, I use it for `rm -rf`'ing.)

**Comment by ile** [comment]
Ok, got a bit different variation of this error, see the attached file.

There is some "garbage" in the log file.

The error in the log file refers to the file `/var/lib/arangodb3/databases/database-374539/collection-7342-2738162157`, which is empty:

```
root@pc:/var/lib/arangodb3/databases/database-374539/collection-7342-2738162157# ls -al
total 8
drwxr-xr-x  2 arangodb arangodb 4096 tammi 17 05:35 .
drwxrwxrwx 31 arangodb arangodb 4096 tammi 17 05:35 ..
-rw-r-----  1 arangodb arangodb    0 tammi 17 05:35 parameter.json
```




[arangod.log](https://github.com/arangodb/arangodb/files/1637660/arangod.log)

**Comment by jsteemann** [comment]
The logfile contains some null bytes after the last log message and before the restart.
The collection directory has a "parameter.json" file which has a length of 0 bytes, meaning that writes to this file have not made it to disk either.

Normally at least the "parameter.json" files should be written with a final fsync at the end, so the data is expected to be on disk after the write. Can you check in your configuration whether the option "database.force-sync-properties" is explicitly set to false?

**Comment by ile** [comment]
Doesn't seem to be in the /etc/arangodb3/arangod.conf at least (file copied to .txt so it can be attached here).

[arangod.conf.txt](https://github.com/arangodb/arangodb/files/1638545/arangod.conf.txt)

**Comment by jsteemann** [comment]
@ile : right, so it should use the default value (use fsync when writing the parameter.json files to disk).
We'll try to reproduce this with the same setup.
Are you using Ubuntu 16.10? Do you know which kernel version (don't think it will make a difference, but just to be sure).

**Comment by ile** [comment]
I'm using Ubuntu 16.04.

```
ile@pc:/etc/arangodb3$ uname -a
Linux pc 4.4.0-109-generic #132-Ubuntu SMP Tue Jan 9 19:52:39 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
ile@pc:/etc/arangodb3$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```

Also, the disk is Kingston SSD (120GB), if that could help anything.

**Comment by jsteemann** [comment]
Thanks.

**Comment by ile** [comment]
One more bit of info: I'm using [AHCI](https://en.wikipedia.org/wiki/Advanced_Host_Controller_Interface) and the motherboard (Gigabyte P35C-DS3R) is quite old, and I remember reading, that there were some problems with the early AHCI implementations. If it's a hardware problem, this could perhaps affect it.

**Comment by okeuday** [comment]
@jsteemann I happened to be looking at this problem and it looks like you are overwriting a file, which is never an atomic action.  You need to write to a new file and do a `rename` (move), since that is an atomic action (if it is a real filesystem, not NFS).

**Comment by jsteemann** [comment]
By coincidence, we have done some research yesterday night as well, and found a way to reproduce the problem. At least for the VERSION file I think the overwriting is not the problem (the file disappears completely), but it may be the case for other files. I'll get back when the fix is ready.

**Comment by jsteemann** [comment]
We have a fix for this as in the linked PRs above.
Until there is a release containing the fix, anyone is more than welcome to try the fix by building that bugfix branch.

**Comment by jsteemann** [comment]
The disappearing VERSION files issue should be addressed and fixed in releases 3.2.12 and 3.3.3 (both not published yet).
I am not sure if the zero byte `parameters.json` file is related to this. It may be the case, but we are unable to reproduce this particular issue.
Can you try if 3.3.3 fixes the problem after it has been released? Thanks!

**Comment by ile** [comment]
Ok, sure will. Thanks.

I have seen the zero byte parameters.json file issue only once. The VERSION file disappearing is a common issue though, it has happened tens of times. So maybe they are different. (Although if the hardware has anything to do with it, it may affect both.)

Creating a stress test so the computer is shut off and then rebooted, with checks if everything is still working might be a way to reproduce even the parameters.json file issue. If this test is automated it could be a way to do it.

**Comment by sleto-it** [comment]
Hi - just to let you know that we have released 3.3.3

Thanks,

**Comment by maxkernbach** [comment]
Hi,

thank you for reporting this bug. The VERSION file remains after a crash in our tests, we think that it is fixed with version 3.3.3. Please reopen this issue in case it does still occur after upgrading to 3.3.3.
