### ISSUE TITLE
Multiple versions installed when upgraded - Community edition

### ISSUE THREAD

**Issue by pmahend1** [arangodb/arangodb#5659]
## my environment running ArangoDB
I'm using ArangoDB version:
- [x] 3.3

Mode:
- [x] Single-Server

Storage-Engine:
- [x] rocksdb

On this operating system:
- [x] Windows, version: 10

### this is an installation-related issue:
I started using ArangoDB community edition on my windows 10. Started with 3.3.3 , when new versions for bug fixes I upgraded from the link that is provided and running installer. Instead of updating version  of current ArangoDB , it creates new standalone application on windows. This is same for community edition as well.

Please see below screenshot.
![untitled](https://user-images.githubusercontent.com/21352870/41815149-c9dbb78a-772f-11e8-9da5-9b565b15dffb.png)

I can switch to different versions on web interface just by starting arangod.exe (Arango Server) for that instance. I can see multiple file locations as below

- C:\Program Files\ArangoDB3 3.X.X\etc\arangodb3
- C:\Users\Prateek\AppData\Local\ArangoDB3-client 3.X.X

It gets confusing to decide where my database files are associated with.

**Expected behavior :** Need to upgrade current version , not have multiple versions.

**Comment by Simran-B** [comment]
The Windows installer creates a new folder for the binaries and other server-related files each time in `C:\Program Files\ArangoDB 3 x.x.x`, which I think is intended - you can't replace files while they are on use under Windows (this is different in Linux systems).

The data files however are shared by default (it's the install for all users and as service option). They reside in `C:\ProgramData\ArangoDB`. Foxx services are in `C:\ProgramData\ArangoDB-apps`.

After installation of a bug fix release, you can remove the binaries from the old version via the control panel > programs and apps using the uninstaller. Don't tick the option to remove databases and apps though!

**Comment by OmarAyo** [comment]
Hi @pmahend1 

Was Simran's message useful for you? Is there anything else we can do to support you in this ticket?

Best,

**Comment by pmahend1** [comment]
@OmarAyo I have already done uninstalling older versions safely.

Raised bug as it was suggested on [Stackoverflow question](https://stackoverflow.com/questions/50938411/arangodb-where-database-files-are-stored)

It would be nice to have feature to upgrade existing software by prompting closure of running application.

**Comment by sleto-it** [comment]
This should be solved starting from 3.4.0-RC.3

Please could you check 3.4.0-RC.3 when it is released?

Thanks,

**Comment by pmahend1** [comment]
@sleto-it Sure. will check and update.

**Comment by pmahend1** [comment]
I could see DB being migrated or something being shown on command prompt while upgrade software was running .

I think its somewhat fixed. I can still see multiple versions on my desktop.

![image](https://user-images.githubusercontent.com/21352870/47571103-b89a8b80-d905-11e8-98f6-1a7ef081e9ac.png)

I can run the old ArangoDB server excutable but it wont start old server, one thing new version is locking DB files so that old version arangod.exe wont run.

I can run old arangosh.exe but good thing it points to new db server.

```
C:\Program Files\ArangoDB3 3.3.10\usr\bin>arangod.exe
2018-10-26T13:57:22Z [572] INFO {authentication} Jwt secret not specified, generating...
2018-10-26T13:57:22Z [572] INFO ArangoDB 3.3.10 [win64] 64bit, using build tags/v3.3.10-0-g902a980389, VPack 0.1.30, RocksDB 5.6.0, ICU 58.1, V8 5.7.492.77, OpenSSL 1.0.2a 19 Mar 2015
2018-10-26T13:57:22Z [572] INFO using storage engine mmfiles
2018-10-26T13:57:22Z [572] INFO {cluster} Starting up with role SINGLE
2018-10-26T13:57:22Z [572] INFO {authentication} Authentication is turned on (system only)
2018-10-26T13:57:22Z [572] FATAL failed to remove an abandoned lockfile in the database directory, please check the file permissions of the lockfile 'C:\ProgramData\ArangoDB\LOCK': system error

C:\Program Files\ArangoDB3 3.3.10\usr\bin>arangosh
Please specify a password:

                                       _
  __ _ _ __ __ _ _ __   __ _  ___  ___| |__
 / _` | '__/ _` | '_ \ / _` |/ _ \/ __| '_ \
| (_| | | | (_| | | | | (_| | (_) \__ \ | | |
 \__,_|_|  \__,_|_| |_|\__, |\___/|___/_| |_|
                       |___/

arangosh (ArangoDB 3.3.10 [win64] 64bit, using build tags/v3.3.10-0-g902a980389, VPack 0.1.30, RocksDB 5.6.0, ICU 58.1, V8 5.7.492.77, OpenSSL 1.0.2a 19 Mar 2015)
Copyright (c) ArangoDB GmbH

Pretty printing values.
Connected to ArangoDB 'http+tcp://127.0.0.1:8529' version: 3.4.0-rc.3 [server], database: '_system', username: 'root'

Please note that a new bugfix version '3.3.19' is available
Type 'tutorial' for a tutorial or 'help' to see common examples
127.0.0.1:8529@_system>
127.0.0.1:8529@_system> exit

Uf wiederluege! σåìΦºü∩╝ü Na shledanou! Auf Wiedersehen! Bye Bye! Adiau! ┬íHasta luego! ╬ò╬╣╧é ╧ä╬┐ ╬╡╧Ç╬▒╬╜╬╣╬┤╬╡╬»╬╜!
╫£╫ö╫¬╫¿╫É╫ò╫¬! Arrivederci! Tot ziens! Adj├╢! Au revoir! πüòπéêπüåπü¬πéë ╨ö╨╛ ╤ü╨▓╨╕╨┤╨░╨╜╨╕╤Å! At├⌐ Breve! ╪«╪»╪º╪¡╪º┘ü╪╕! Uz redz─ô┼íanos!
```


**But what if I run arangod.exe from admin privileges?**

```
C:\Program Files\ArangoDB3 3.3.10\usr\bin>arangod.exe
2018-10-26T14:06:17Z [11424] INFO {authentication} Jwt secret not specified, generating...
2018-10-26T14:06:17Z [11424] INFO ArangoDB 3.3.10 [win64] 64bit, using build tags/v3.3.10-0-g902a980389, VPack 0.1.30, RocksDB 5.6.0, ICU 58.1, V8 5.7.492.77, OpenSSL 1.0.2a 19 Mar 2015
2018-10-26T14:06:17Z [11424] INFO using storage engine mmfiles
2018-10-26T14:06:17Z [11424] INFO {cluster} Starting up with role SINGLE
2018-10-26T14:06:17Z [11424] INFO {authentication} Authentication is turned on (system only)
2018-10-26T14:06:17Z [11424] INFO running WAL recovery (1 logfiles)
2018-10-26T14:06:17Z [11424] INFO replaying WAL logfile 'C:\ProgramData\ArangoDB\journals\logfile-13518334.db' (1 of 1)
2018-10-26T14:06:17Z [11424] INFO WAL recovery finished successfully
2018-10-26T14:06:18Z [11424] ERROR In database "Foo": Database directory version (30400) is higher than current version (30310).
2018-10-26T14:06:18Z [11424] ERROR In database "Foo": It seems like you are running ArangoDB on a database directory that was created with a newer version of ArangoDB. Maybe this is what you wanted but it is not supported by ArangoDB.
2018-10-26T14:06:18Z [11424] ERROR In database "Fighters": Database directory version (30400) is higher than current version (30310).2018-10-26T14:06:18Z [11424] ERROR In database "Fighters": It seems like you are running ArangoDB on a database directory that was created with a newer version of ArangoDB. Maybe this is what you wanted but it is not supported by ArangoDB.
2018-10-26T14:06:18Z [11424] ERROR In database "Nirvana": Database directory version (30400) is higher than current version (30310).
2018-10-26T14:06:18Z [11424] ERROR In database "Nirvana": It seems like you are running ArangoDB on a database directory that was created with a newer version of ArangoDB. Maybe this is what you wanted but it is not supported by ArangoDB.
2018-10-26T14:06:18Z [11424] ERROR In database "_system": Database directory version (30400) is higher than current version (30310).
2018-10-26T14:06:18Z [11424] ERROR In database "_system": It seems like you are running ArangoDB on a database directory that was created with a newer version of ArangoDB. Maybe this is what you wanted but it is not supported by ArangoDB.
2018-10-26T14:06:18Z [11424] INFO using endpoint 'http+tcp://127.0.0.1:8529' for non-encrypted requests
2018-10-26T14:06:20Z [11424] INFO Please note that a new bugfix version '3.3.19' is available
2018-10-26T14:06:20Z [11424] INFO ArangoDB (version 3.3.10 [win64]) is ready for business. Have fun!
```

then I was able to connect via 3.3.10 (old version) with warning.

![image](https://user-images.githubusercontent.com/21352870/47571733-4aef5f00-d907-11e8-97b5-7673a3c40185.png)

**Comment by Simran-B** [comment]
@pmahend1 How I believe it is expected to work is, that if you manually start the uninstaller and remove the ArangoDB instance, then the start menu entries should get removed along with the binaries. But this requires 3.4+. The uninstallation of older versions should remove the binaries as expected, but leaves the start menu entries behind.

If you overwrite an existing installation with new binaries using the installer, then most but not all files should get overwritten, but you will end up with start menu and app entries for both versions.

**Comment by pmahend1** [comment]
I did have only v3.3.10 when installing 3.4.

I uninstalled v3.3.10 now , I will carefully uninstall 3.4 and install 3.3.19 and then install 3.4 again.

Wondering why it should work only with immediate previous one version 3.3.19 .

It gets confusing . So I guess best solution at the moment is to uninstall any existing software without deleting database files and install latest one with importing/retaining old database files.

**Comment by Simran-B** [comment]
Uninstalling while keeping the database files and then installing the new version is the cleanest option in my opinion, yes.

Otherwise we would need to make the installer run the uninstaller of the previous version automatically in the background I suppose. But there are quite a few additional stumbling blocks, so not sure if we can rework all that for RC4.

**Comment by pmahend1** [comment]
Yeah. that would require to force close all db executables.

To not mess up existing db; users should still be informed to close the db server and instances.I am not sure how copying database files while it still running is reliable. There are possibilities to corrupt old db files if done while installation ?

**Comment by dothebart** [comment]
Native Windows Support has been dropped with ArangoDB 3.12.
