### ISSUE TITLE
AQL timeout

### ISSUE THREAD

**Issue by tkallioras** [arangodb/arangodb#5884]
## My Environment

* __ArangoDB Version__:        3.3.12 Enterprise
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Local Cluster
* __Configuration__:               
* __Infrastructure__:               
* __Operating System__:        MacOS 10.14 beta
* __Used Package__:              Docker - official Docker library

I have this AQL query:

```
WITH @@usersCollection, @@emailsCollection, @@userToEmailEdges

LET user = FIRST(
INSERT @user IN @@usersCollection RETURN NEW
)

INSERT @email IN @@emailsCollection
INSERT @edge IN @@userToEmailEdges
RETURN user
```

Each collection has a replication factor of 2 and number of shards is 40. The edge points from `usersCollection` to `emailsCollection`

With version 3.3.11 everything was working correctly. In version 3.3.12 I get the following error:

`AQL: timeout, cluster node: 'PRMR-5d53c80e-061d-4cc0-8178-15018555cf8f', shard: 's4010815', endpoint: 'tcp://192.168.1.104:8540', error: 'timeout in cluster operation' (while executing)
`

**Comment by graetzer** [comment]
this should not happen, can you post the query explain output ? 
Ideally the one from 3.3.11 and from 3.3.12

As a side note: it seems like you should be using the normal document APIs, these should be _much_ more efficient in your case

**Comment by tkallioras** [comment]
> As a side note: it seems like you should rather be using the normal document APIs, these should be much more efficient in your case

I was under the impression that the AQL queries had 'transactional' properties (i.e. everything that happens within a query happens in a transactional fashion). I found some relevant comments in this [issue](https://github.com/arangodb/arangodb/issues/1346) and more specifically I am referring to this comment:

> When executed in isolation, db._query() will issue a single AQL query in a transactional fashion.

My rationale is that if I issue three different backend calls to the document API (one for the user, one for the email and one for the edge connecting those two), then if something happens in between those calls, then I will be left with a dangling user, without an email and a respective edge. Or with a user, an email but no edge. Is there something that I misunderstand here?

I will shortly post the two query explains.

**Comment by graetzer** [comment]
please see https://docs.arangodb.com/3.3/Manual/Transactions/Limitations.html#in-clusters

**Comment by tkallioras** [comment]
**3.3.11 Enterprise:**

```
Query string:
 		LET user = FIRST(
 		INSERT @user IN @@usersCollection RETURN NEW
 		)
 		INSERT @email IN @@emailsCollection
 		INSERT @edge IN @@userToEmailEdges
 		RETURN user

Execution plan:
 Id   NodeType          Site       Est.   Comment
  1   SingletonNode     COOR          1   * ROOT
  6   SubqueryNode      COOR          1     - LET #1 = ...   /* subquery */
  2   SingletonNode     DBS           1       * ROOT
  3   CalculationNode   DBS           1         - LET #6 = ""   /* json expression */   /* const assignment */
  4   InsertNode        DBS           1         - INSERT #6 IN users
 23   RemoteNode        COOR          1         - REMOTE  /* shard: s4010779 */
 24   GatherNode        COOR          1         - GATHER 
  5   ReturnNode        COOR          1         - RETURN $NEW
  7   CalculationNode   COOR          1     - LET user = FIRST(#1)   /* simple expression */
  8   CalculationNode   COOR          1     - LET #8 = ""   /* json expression */   /* const assignment */
 17   ScatterNode       COOR          1     - SCATTER
 18   RemoteNode        DBS           1     - REMOTE
  9   InsertNode        DBS           0     - INSERT #8 IN emails
 19   RemoteNode        COOR          0     - REMOTE  /* shard: s4010820 */
 20   GatherNode        COOR          0     - GATHER 
 13   ScatterNode       COOR          0     - SCATTER
 14   RemoteNode        DBS           0     - REMOTE
 11   InsertNode        DBS           0     - INSERT #8 IN userToEmailEdges
 15   RemoteNode        COOR          0     - REMOTE  /* shard: s4010861 */
 16   GatherNode        COOR          0     - GATHER 
 12   ReturnNode        COOR          0     - RETURN user

Indexes used:
 none

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   remove-redundant-calculations
  3   remove-unnecessary-calculations
  4   remove-data-modification-out-variables
  5   move-calculations-down
  6   scatter-in-cluster
  7   remove-unnecessary-remote-scatter
  8   restrict-to-single-shard

Write query options:
 Option                   Value
 ignoreErrors             false
 waitForSync              false
 nullMeansRemove          false
 mergeObjects             true
 ignoreDocumentNotFound   false
 readCompleteInput        false
 useIsRestore             false
 consultAqlWriteFilter    false
```

**3.3.12 Enterprise:**

```
Query string:
 		LET user = FIRST(
 		INSERT @user IN @@usersCollection RETURN NEW
 		)
 		INSERT @email IN @@emailsCollection
 		INSERT @edge IN @@userToEmailEdges
 		RETURN user

Execution plan:
 Id   NodeType          Site       Est.   Comment
  1   SingletonNode     DBS           1   * ROOT
  6   SubqueryNode      DBS           1     - LET #1 = ...   /* subquery */
  2   SingletonNode     DBS           1       * ROOT
  3   CalculationNode   DBS           1         - LET #6 = ""   /* json expression */   /* const assignment */
  4   InsertNode        DBS           1         - INSERT #6 IN users
 19   RemoteNode        COOR          1         - REMOTE  /* shard: s4010061 */
 20   GatherNode        COOR          1         - GATHER 
  5   ReturnNode        COOR          1         - RETURN $NEW
  7   CalculationNode   DBS           1     - LET user = FIRST(#1)   /* simple expression */
  8   CalculationNode   DBS           1     - LET #8 = ""   /* json expression */   /* const assignment */
  9   InsertNode        DBS           0     - INSERT #8 IN emails
 23   RemoteNode        COOR          0     - REMOTE  /* shard: s4010268 */
 24   GatherNode        COOR          0     - GATHER 
 13   DistributeNode    COOR          0     - DISTRIBUTE
 14   RemoteNode        DBS           0     - REMOTE
 11   InsertNode        DBS           0     - INSERT #8 IN userToEmailEdges
 15   RemoteNode        COOR          0     - REMOTE  /* shard: s4010432 */
 16   GatherNode        COOR          0     - GATHER 
 12   ReturnNode        COOR          0     - RETURN user

Indexes used:
 none

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   remove-redundant-calculations
  3   remove-unnecessary-calculations
  4   remove-data-modification-out-variables
  5   move-calculations-down
  6   distribute-in-cluster
  7   scatter-in-cluster
  8   restrict-to-single-shard

Write query options:
 Option                   Value
 ignoreErrors             false
 waitForSync              false
 nullMeansRemove          false
 mergeObjects             true
 ignoreDocumentNotFound   false
 readCompleteInput        false
 useIsRestore             false
 consultAqlWriteFilter    false
 ignoreRevs               true
```

**Comment by tkallioras** [comment]
Thanks for the link. So, performance-wise, using the document API would be faster than issuing the query API?

**Comment by graetzer** [comment]
yes should be a lot faster

**Comment by tkallioras** [comment]
Is there any documentation where I can find performance characteristics of each API so that I can make more informed decisions when designing the communication with the database?

**Comment by ObiWahn** [comment]
Here is an example that shows that the cluster is probably still broken in 3.3.12 and devel. The restrict to single shard rule does not work for both branches as it does not work for 3.3.11. Single shard optimization  seems to work in the explain if user, email and edge are empty strings. Even when the  restrict to single shard rule does not work the result must not contain #numberOfShards elements.

```
( debug_script = function(){

query=`WITH @@usersCollection, @@emailsCollection, @@userToEmailEdges

         LET user = FIRST(
                          INSERT @user IN @@usersCollection RETURN NEW
                         )

         INSERT @email IN @@emailsCollection
         INSERT @edge IN @@userToEmailEdges
         RETURN user
`

const props = { replicationFactor : 2, numberOfShards :40}


function ensure_coll(name, properties, is_edge){
    var coll = db._collection(name);

    if( coll === null){
        if(is_edge === true){
            coll = db._createEdgeCollection(name, properties)
        } else {
            coll = db._create(name, properties)
        }
    }
    print(coll.properties())
    coll.truncate()
    return coll
}


users = ensure_coll("usersCollection", props)
mails = ensure_coll("emailsCollection", props)
u_to_m = ensure_coll("userToEmailEdges", props, true)

var bind_params = {
 "@usersCollection" : users.name(),
 "@emailsCollection" : mails.name(),
 "@userToEmailEdges" : u_to_m.name(),

 "email" : { mail : "foo@bar.baz" },
 "user" : { name : "foo" },
 "edge" : { _from : users.name() + "/abc", _to : mails.name() + "/abc"}

// "email" : "" ,
// "user" : "",
// "edge" : ""
}


db._explain(query, bind_params)
var res = db._query(query, bind_params)
print("res: ", res.toArray())
print("len: ", res.toArray().length)
print(db._version())

})();
```

**Comment by jsteemann** [comment]
This issue should have been fixed in ArangoDB 3.3.13, which was released recently. 
Can you confirm it works now using that version? Preferably please try this with a fresh collection.

**Comment by tkallioras** [comment]
@jsteemann unfortunately the error persists. I erased the database, and I rerun the same query, and still I get a timeout

**Comment by tkallioras** [comment]
My setup is a local cluster (via arangodb starter) 3.3.13 enterprise

**Comment by ObiWahn** [comment]
I can execute the query without a problem. How and how often is the query executed?

**Comment by tkallioras** [comment]
@ObiWahn I am posting the query explanation from ArangoDB Web UI:

```
Query string:
 		LET user = FIRST(
 			INSERT @user IN @@usersCollection
 			RETURN NEW
 		)
 		INSERT @email IN @@emailsCollection
 		INSERT @edge IN @@userToEmailEdges
 		RETURN user._key

Execution plan:
 Id   NodeType          Site       Est.   Comment
  1   SingletonNode     DBS           1   * ROOT
  6   SubqueryNode      DBS           1     - LET #1 = ...   /* subquery */
  2   SingletonNode     DBS           1       * ROOT
  3   CalculationNode   DBS           1         - LET #6 = ""   /* json expression */   /* const assignment */
  4   InsertNode        DBS           1         - INSERT #6 IN users
 24   RemoteNode        COOR          1         - REMOTE  /* shard: s5011052 */
 25   GatherNode        COOR          1         - GATHER 
  5   ReturnNode        COOR          1         - RETURN $NEW
 12   CalculationNode   DBS           1     - LET #12 = FIRST(#1).`_key`   /* simple expression */
  8   CalculationNode   DBS           1     - LET #8 = ""   /* json expression */   /* const assignment */
  9   InsertNode        DBS           0     - INSERT #8 IN emails
 20   RemoteNode        COOR          0     - REMOTE  /* shard: s5011259 */
 21   GatherNode        COOR          0     - GATHER 
 14   DistributeNode    COOR          0     - DISTRIBUTE
 15   RemoteNode        DBS           0     - REMOTE
 11   InsertNode        DBS           0     - INSERT #8 IN userToEmailEdges
 16   RemoteNode        COOR          0     - REMOTE  /* shard: s5011507 */
 17   GatherNode        COOR          0     - GATHER 
 13   ReturnNode        COOR          0     - RETURN #12

Indexes used:
 none

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   remove-redundant-calculations
  3   remove-unnecessary-calculations
  4   remove-data-modification-out-variables
  5   move-calculations-down
  6   distribute-in-cluster
  7   restrict-to-single-shard

Write query options:
 Option                   Value
 ignoreErrors             false
 waitForSync              false
 nullMeansRemove          false
 mergeObjects             true
 ignoreDocumentNotFound   false
 readCompleteInput        false
 useIsRestore             false
 consultAqlWriteFilter    false
 ignoreRevs               true
```

The error is the following:

`Query: AQL: timeout, cluster node: 'PRMR-c8212170-be9b-4c19-b0f4-b979a87d882d', shard: 's5011259', endpoint: 'tcp://192.168.1.104:8540', error: 'timeout in cluster operation' (while executing)`

It also happens when I execute the same query through the golang driver.

**Comment by ObiWahn** [comment]
We have trouble reproducing the issue so here are a few things that we ask you to do: 

- Please verify that all servers are up before and after the query.
- Please try this with a brand new cluster.
- Please provide the exact arguments that you use for the starter.
- Please try the debug function that I have posted above. Copy it into a file and run it using `require("internal").load("path/to/file")`.
- Please modify the function to use the bind parameters and options that you use, create the collections in the very same way you do and post it back into this issue.

**Comment by ObiWahn** [comment]
This PR is a potential fix for #6036. We have been able to reproduce the issue in the web-ui. After applying the patch the problem was gone in the.

**Comment by ObiWahn** [comment]
@tkallioras are you able to confirm that the bug is fixed? Please re-open the ticket in case you experience still trouble with the query.

**Comment by tkallioras** [comment]
@ObiWahn In 3.4.0-RC.1 the issue is solved
